### ISSUE TITLE
Add back "miscellaneous" matplotlib colormaps

### ISSUE THREAD

**Issue by mickaellalande** [lukelbd/proplot#123]
It would be nice to have by default all the colormaps from Matplotlib (https://matplotlib.org/examples/color/colormaps_reference.html) in particular the `jet` one for example that I was used to pick, because more visible than the `Spectral` one in Proplot. But the `terrain` one is also useful, etc. I don't know if there is particular attention for colorblind people and if it goes in that way or not (I don't have any knowledge on that)?

**Comment by lukelbd** [comment]
So the reason we removed jet is to strong-arm users into using "perceptually uniform" colormaps -- check out [this workshop](https://github.com/bradyrx/climate_science_colormapping) @bradyrx and I hosted (see the slides in the "powerpoint" folder and the notebooks in the "notebooks" folder).

But I think you're right, it is probably preferable to keep these colormaps "resistered" but just *hide* them from the [colormap table](https://proplot.readthedocs.io/en/latest/colormaps.html#Included-colormaps) (I do the same thing by hiding matplotlib's [CSS colors](https://matplotlib.org/3.1.1/gallery/color/named_colors.html) to push users toward [xkcd and crayola colors](https://proplot.readthedocs.io/en/latest/colors_fonts.html#Included-colors)). Also topographic colormaps kind of defy the typical colormap categorization into sequantial/diverging/qualitative, so even though they are generally not "perceptually uniform" there's no reason they should be deleted.

I will add back the colormaps then maybe add an `ignore` keyword arg to `show_cmaps` that can be used to ignore certain categories. By default, it will ignore the maps in the "[Miscellaneous colormaps](https://matplotlib.org/examples/color/colormaps_reference.html)" category.

**Comment by mickaellalande** [comment]
Ok, great thanks for the explanations, I was a bit expecting this kind of answer, but it was still unclear for me. Because many "old" supervisors will ask for this `jet` colormap to "see something", however next time I will show them your presentation :rofl:.

**Comment by lukelbd** [comment]
This was fixed by ce4ef6a0. "Bad" colormaps are no longer deleted
