### ISSUE TITLE
x axis labeling disappears when using twinx()

### ISSUE THREAD

**Issue by bradyrx** [lukelbd/proplot#127]
#### Code sample, a copy-pastable example if possible
A "[Minimal, Complete and Verifiable Example](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)" will make it much easier for maintainers to help you.

```python
import proplot as plot
import numpy as np
import xarray as xr

times = np.arange(1990, 2000)
data = xr.DataArray(np.random.rand(len(times)), dims=['time'], coords=[times])

f, ax = plot.subplots(aspect=2)
ax.plot(data.time, data)

twinax = ax.twinx()

# twinax.format(xlocator=1)
ax.format(xticks=np.arange(1990, 2000, 2))
```

#### Actual result vs. expected result

Using `twinx()`, the tick labeling disappears on the twin axis. This happens for datetime and normal numbers. Using `xticks`/`xlocator` on the main axis or `twinax` instance changes the ticks but does not produce labels.

**Comment by bradyrx** [comment]
You can actually see this in the RC settings demo on the docs on the right subplot.

https://proplot.readthedocs.io/en/latest/basics.html#Changing-rc-settings

**Comment by lukelbd** [comment]
Which version are you using? Is this the "dev" release?

**Comment by bradyrx** [comment]
I'm using the 0.0.5 that's on pip now.

**Comment by lukelbd** [comment]
Actually this is intended behavior. Counterintuitively, the matplotlib [`twinx`](https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.twinx.html#matplotlib.axes.Axes.twinx) function generates two *y* axes with a shared "twin" *x* axes, and ProPlot ensures the shared axes ticks, tick labels, and axis labels are *invisible* so you don't accidentally draw multiple tick labels or labels from both "twins" on top of each other.

As you have demonstrated, this naming is really confusing for users, so proplot introduces the more intutively-named [`altx`](https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.twinx.html#matplotlib.axes.Axes.twiny) function for making an "alternate x axes" and `alty` for making an "alternate y axes".

**Comment by zxdawn** [comment]
@lukelbd I met the same problem today.

If I use the same example as @bradyrx showed above without twin, the xaxis tick labels are correct:
![image](https://user-images.githubusercontent.com/30388627/76145384-fc89cd00-60c3-11ea-8bae-cd28afb6a365.png)

But, if I add the the twinx(), the tick labels disappeared:
![image](https://user-images.githubusercontent.com/30388627/76145401-20e5a980-60c4-11ea-8921-acfe06628af0.png)

This is the actual case I met: I want to plot two kinds of profiles with pressure, but I couldn't let the pressure ticks labels show up ...
![image](https://user-images.githubusercontent.com/30388627/76145445-7621bb00-60c4-11ea-8e0e-b323fd599c4e.png)

**Comment by bradyrx** [comment]
> Counterintuitively, the matplotlib twinx function generates two y axes with identical "twin" x axes, and ProPlot ensures the shared axes ticks, tick labels, and axis labels on the secondary x axis are hidden so you don't accidentally draw duplicate labels from both "twins" on top of each other. If you want to set the x axis properties, you should do so on the original axes.

Yes I understand this and agree with you that the naming is bad. I also agree that you shouldn't be able to modify the dual axis so you don't get out-of-phase ticks, clutter, etc. 

The issue, as @zxdawn also mentioned, is that the original axis completely disappears. And in my example, you see that modifying the original axis does nothing to fix this (below with `alty`):

```python
import proplot as plot
import numpy as np
import xarray as xr

times = np.arange(1990, 2000)
data = xr.DataArray(np.random.rand(len(times)), dims=['time'], coords=[times])

f, ax = plot.subplots(aspect=2)
ax.plot(data.time, data)

twinax = ax.alty()

# twinax.format(xlocator=1)
ax.format(xticks=np.arange(1990, 2000, 2))
```

I agree you shouldn't be able to modify the twin axis, but it shouldn't render the original axis unreadable. It's still important to see the ticks, time series labeling, etc.

**Comment by lukelbd** [comment]
My bad! I see now, this definitely is a major problem. I will address this before the end of the weekend.

**Comment by lukelbd** [comment]
Sorry for the wait guys; I had to step back from proplot for a while and knew this one would be tricky to fix. But it's finally done.

**Comment by zxdawn** [comment]
@lukelbd Thanks for the fix! Will test it for the O3 and Qv profile tomorrow.

**Comment by bradyrx** [comment]
This is great, thanks Luke!

**Comment by zxdawn** [comment]
Works well. Thank Luke!
![proplot_profile](https://user-images.githubusercontent.com/30388627/81928141-661fdd80-9617-11ea-8da0-cc986e895eaa.png)
