### ISSUE TITLE
plot.show() shows empty but f.savefig() works

### ISSUE THREAD

**Issue by zxdawn** [lukelbd/proplot#128]
### Description
For 4K screen, `plot.show()` shows empty figure with default window size and shows too large with full screen mode.

### Steps to reproduce

```python
import proplot as plot
import numpy as np
state = np.random.RandomState(51423)
data = 2*(state.rand(100, 5) - 0.5).cumsum(axis=0)

# Simple plot
f, axs = plot.subplots(ncols=2)
axs[0].plot(data, lw=2)
axs[0].format(xticks=20, xtickminor=False)
axs.format(
    suptitle='Simple subplot grid', title='Title',
    xlabel='x axis', ylabel='y axis'
)

plot.show()
```

**Expected behavior**:
Just like `plt.show()`

**Actual behavior**:
- default window size:
![image](https://user-images.githubusercontent.com/30388627/76133292-7bdeb880-6052-11ea-98b9-1c7406498f63.png)

- full screen
![image](https://user-images.githubusercontent.com/30388627/76133465-38d11500-6053-11ea-8b5f-ffa8475656b4.png)

### Equivalent steps in matplotlib
```python
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
from matplotlib import rcParams
import numpy as np
state = np.random.RandomState(51423)
data = 2*(state.rand(100, 5) - 0.5).cumsum(axis=0)

# Simple plot
f, axs = plt.subplots(ncols=2)
ax = axs[0]
ax.plot(data)
ax.xaxis.set_major_locator(mticker.MultipleLocator(20))
ax.tick_params(axis='y', which='minor')#, bottom=True)
ax.set_xlabel('x axis')
ax.set_ylabel('y axis')

plt.show()
```
- default
![image](https://user-images.githubusercontent.com/30388627/76133628-168bc700-6054-11ea-89dd-dab5e5859d7f.png)

- full screen
![image](https://user-images.githubusercontent.com/30388627/76133635-20152f00-6054-11ea-9d1c-99bfef8fdc45.png)

### Proplot version
0.5.0

**Comment by zxdawn** [comment]
It seems this is the problem of matplotlib: https://github.com/matplotlib/matplotlib/issues/12074.

But, if I use Equivalent steps in matplotlib, it works fine. So, maybe there's something inside proplot causing the issue.

**Comment by zxdawn** [comment]
I've tried the suggestion in that matplotlib issue (using matplotlib 2.1.2):
```
conda create -n test_matplotlib -c conda-forge python=3.7 matplotlib=2.1.2 numpy proplot
```

However, `proplot needs higher version of matplotlib`:
```
Traceback (most recent call last):                                                                                                        
  File ".\test_proplot.py", line 12, in <module>                                                                                          
    f, axs = plot.subplots(ncols=2)                                                                                                       
  File "E:\miniconda3\envs\test_matplotlib\lib\site-packages\proplot\subplots.py", line 2397, in subplots                                 
    **kwargs                                                                                                                              
  File "E:\miniconda3\envs\test_matplotlib\lib\site-packages\matplotlib\pyplot.py", line 539, in figure                                   
    **kwargs)                                                                                                                             
  File "E:\miniconda3\envs\test_matplotlib\lib\site-packages\matplotlib\backend_bases.py", line 170, in new_figure_manager                
    fig = fig_cls(*args, **kwargs)                                                                                                        
  File "E:\miniconda3\envs\test_matplotlib\lib\site-packages\proplot\subplots.py", line 941, in __init__                                  
    gridspec = GridSpec(self, **gridspec_kw)                                                                                              
  File "E:\miniconda3\envs\test_matplotlib\lib\site-packages\proplot\subplots.py", line 328, in __init__                                  
    figure=figure, **kwargs                                                                                                               
TypeError: __init__() got an unexpected keyword argument 'figure'   
```

**Comment by lukelbd** [comment]
Sorry I am replying to this so late. Do you know which backend you were using when this happened? Could you print the result of

```python
print(plot.rc['backend'])
```

This looks like a backend issue. The [automatic figure resizing feature](https://proplot.readthedocs.io/en/latest/subplots.html#Automatic-figure-size) is difficult to accomplish with every backend, and ProPlot is unfortunately not tested with all of them. Note you should have success with the `qt` backend and the jupyter notebook `inline` backends.

**Comment by zxdawn** [comment]
@lukelbd Thanks! I tested `plot.rc['backend'] = 'Qt4Agg'`, it looks much better now.

- default window size:
![image](https://user-images.githubusercontent.com/30388627/81489127-aba17b00-92a4-11ea-991d-a8e2f519d52f.png)


- full screen:
![image](https://user-images.githubusercontent.com/30388627/81489130-b3611f80-92a4-11ea-86b5-9d220e50813b.png)
