### ISSUE TITLE
Metric string for subplot width doesn't work

### ISSUE THREAD

**Issue by bradyrx** [lukelbd/proplot#13]
With the most recent commit, trying to set a string width in metric (e.g., "10cm") does not work.

<img width="1227" alt="Screen Shot 2019-03-25 at 11 14 06 PM" src="https://user-images.githubusercontent.com/8881170/54973030-d2430c00-4f53-11e9-854d-c7c5d5e63ac6.png">

**Comment by bradyrx** [comment]
Note this also breaks when calling a journal keyword that involves 'mm', such as agu#.

**Comment by lukelbd** [comment]
Commit 7dda3b5 should fix it. I added meters as a unit. Regexes are hard.
