### ISSUE TITLE
Would you add the "readshapefile" method in proplot?

### ISSUE THREAD

**Issue by sfhua** [lukelbd/proplot#137]
### Description

[Description of the bug or feature.]

### Steps to reproduce

A "[Minimal, Complete and Verifiable Example](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)" will make it much easier for maintainers to help you.

```python
# your code here
# we should be able to copy-paste this into python and exactly reproduce your bug
```

**Expected behavior**: [What you expected to happen]

**Actual behavior**: [What actually happened]

### Equivalent steps in matplotlib

Please make sure this bug is related to a specific proplot feature. If you're not sure, try to replicate it with the [native matplotlib API](https://matplotlib.org/3.1.1/api/index.html). Matplotlib bugs belong on the [matplotlib github page](https://github.com/matplotlib/matplotlib).

```python
# your code here, if applicable
```

### Proplot version

Paste the result of `import proplot; print(proplot.version)` here.

**Comment by lukelbd** [comment]
Yep at some point I'd like to add extra basemap features to [`ProjectionAxes.format()`](https://proplot.readthedocs.io/en/latest/api/proplot.axes.ProjAxes.format.html#proplot.axes.ProjAxes.format). There's an open issue under this category: #36. 

But for the time being, you can interact with the `basemap.Basemap` object directly using  e.g.

```python
fig, ax = plot.subplots(proj='robin', basemap=True)
ax.projection.readshapefile(...)
```

The [`projection` attribute](
https://proplot.readthedocs.io/en/latest/api/proplot.axes.BasemapAxes.html#proplot.axes.BasemapAxes) stores the `basemap.Basemap` instance for `BasemapAxes` and the `cartopy.crs.Projection` instance for `GeoAxes`.

**Comment by lukelbd** [comment]
Going to close this because I think it is covered by issue #36.
