### ISSUE TITLE
select part colormap to merge new colormap

### ISSUE THREAD

**Issue by wangrenz** [lukelbd/proplot#138]
Hi:
    How can slice a part of colormaps to merge a new colormap?

**Comment by lukelbd** [comment]
Do you mean you want to combine pieces of existing colormaps? You can use `plot.Colormap` and the `left` and `right` keyword arguments. [This page](https://proplot.readthedocs.io/en/latest/colormaps.html#Modifying-colormaps) has some examples but here's one for this special case:

```python
part1 = plot.Colormap('Blues', left=0.2, right=0.8)
part2 = plot.Colormap('Reds', left=0.5, right=1)
cmap = plot.Colormap(part1, part2)  # merge the maps
```

In a future version of proplot you will be able to pass lists of floats to `left` and `right` and apply different slicing operations each colormap individually (see #84). For example:

```python
cmap = plot.Colormap('Blues', 'Reds', left=(0.2, 0.5), right=(0.8, 1))
```

But I think that's covered by #84, so closing this issue for now.
