### ISSUE TITLE
Poll: import proplot as pplt

### ISSUE THREAD

**Issue by stefraynaud** [lukelbd/proplot#139]
### Description

You made the choice to shortcut import proplot with plot

```python
import proplot as plot
```
I think:

* ``plot`` is a too generic name
* it is not easy to swith from ``pyplot`` to ``proplot``, and the reverse.

How about replacing the alias with ``pplt`` which is closer to ``plt`` and prevent any sort of ambiguity?
```python
import proplot as pplt
```

**Comment by Ntkrell** [comment]
I personally don't have any issue with `import proplot as plot`; it's straight-forward enough.

**Comment by lukelbd** [comment]
>plot is a too generic name
>it is not easy to swith from pyplot to proplot, and the reverse.

@stefraynaud I guess you mean it's hard to switch between `plot` and `plt` with a search-replace in your IDE? I think searching `plot.` (with the trailing period) and replacing `plt.` would do the trick.

Fair points though. I don't really feel strongly one way or the other.  I made a poll and readers of this thread should feel free to add their vote below. If `import proplot as plot` or `don't care` wins I'll keep things the same :)

[![](https://api.gh-polls.com/poll/01E5NGMJBCHYT0BPAEFM57QZY7/import%20proplot%20as%20plot)](https://api.gh-polls.com/poll/01E5NGMJBCHYT0BPAEFM57QZY7/import%20proplot%20as%20plot/vote)
[![](https://api.gh-polls.com/poll/01E5NGMJBCHYT0BPAEFM57QZY7/import%20proplot%20as%20pplt)](https://api.gh-polls.com/poll/01E5NGMJBCHYT0BPAEFM57QZY7/import%20proplot%20as%20pplt/vote)
[![](https://api.gh-polls.com/poll/01E5NGMJBCHYT0BPAEFM57QZY7/import%20proplot%20as%20plt)](https://api.gh-polls.com/poll/01E5NGMJBCHYT0BPAEFM57QZY7/import%20proplot%20as%20plt/vote)
[![](https://api.gh-polls.com/poll/01E5NGMJBCHYT0BPAEFM57QZY7/don%27t%20care)](https://api.gh-polls.com/poll/01E5NGMJBCHYT0BPAEFM57QZY7/don%27t%20care/vote)

**Comment by stefraynaud** [comment]
I voted twice by mistake for the first solution I read the second 😀

**Comment by lukelbd** [comment]
Finally implemented this! The default in all examples is now `import proplot as pplt`. I think the majority voters made the right choice -- since the `pplt` abbreviation stands out more than `plot`, it seems to make proplot code a little more readable.
