### ISSUE TITLE
Zoom into specific region of cartopy projection

### ISSUE THREAD

**Issue by bradyrx** [lukelbd/proplot#14]
I'm getting an error with `proplot` when trying to zoom in to a specific subregion of my cartopy projection. I just want to map the California coastline, but it seems to break due to changes in the axis width. However, this works just fine with `matplotlib`.

**Any tips here?** Should I be using something other than `set_extent` that I can call in `plot.subplots()`? Any thoughts on maintaining the right width/aspect for a zoomed in cartopy subplot? I've had trouble in the past with `matplotlib` to get differing coastal regions to have the same width/height aspect ratio due to being in different latitudes.

**proplot**
```python
f, ax = plot.subplots(width='12cm', proj='cyl')
ax.set_extent([-140, -107, 20, 50], crs=ccrs.PlateCarree())
```

Huge error chain ending in:
```
ValueError: Not enough room for axes (would have width -33.5696). Increase width, or reduce spacings 'left', 'right', or 'wspace'.
```

**matplotlib**
```python
f, ax = plt.subplots(subplot_kw=dict(projection=ccrs.PlateCarree()))
ax.set_extent([-140, -107, 20, 50])
ax.coastlines()
```

![Screen Shot 2019-03-28 at 2 06 38 PM](https://user-images.githubusercontent.com/8881170/55189136-b82b4880-5162-11e9-9f6d-ac9ed678924e.png)

**Comment by lukelbd** [comment]
Does f88b37f fix it?

Cartopy has an annoying bug where the native matplotlib "tight layout" bounding box-detector totally fails if you use `set_extent` to zoom into a projection. This means the proplot "smart tight layout" feature also does not work. I had taken this into account before, but for some reason changed it back.

Now ProPlot should issue a warning telling you to use `tight=False` in your call to `subplots`.

**Comment by lukelbd** [comment]
Not sure about fixing aspect ratios when zooming into a projection... if different coastal regions end up having different widths/heights when you zoom in, I think that is just a function of the map projection coordinates, not anything matplotlib is doing (i.e. 1 map projection unit in the horizontal should always equal 1 map projection unit in the vertical, whether you use basemap or cartopy, because that's how map projections work).

If you're suggesting I should support horizontally/vertically warping cartographic projection coordinates, not sure that's a good idea. If you want your subplots to look the same I might recommend messing with the longitude/latitude bounds, or just using a simple projection like `PlateCarree` and making sure your latitude and/or longitude widths are identical for both regions.

**Comment by bradyrx** [comment]
Thanks, that fixes it! And good points on the same box size. I've basically done it that way in the past--changing domains to make the boxes the same size. But I recall finding some hacky way in basemap to deal with aspect ratios and force them to be the same size. But perhaps that distorted continents, etc. in the end.

**Comment by bradyrx** [comment]
Reopening to discuss the same question for `basemap` plots. While cartopy uses `ax.set_extent()`, basemap uses keywords on the `Basemap()` object. (see https://basemaptutorial.readthedocs.io/en/latest/basemap.html). 

Basically Basemap(llcrnrlon=0, llcrnrlat=30, ...) for example. Any thoughts on how to do this, since you're handling the Basemap object under the hood?

I'm looking to reduce the coverage for a south polar stereo map.

```python
f, ax = plot.subplots(proj='spstere', basemap=True,
                      axwidth='10cm')
ax.pcolormesh(ds.XC, ds.YC, ds.isel(time=10),
              vmin=-10, vmax=10, cmap='RdBu')
ax.format(land=True)
```

![Screen Shot 2019-05-13 at 12 47 51 PM](https://user-images.githubusercontent.com/8881170/57646231-55a8d300-757d-11e9-8c9a-c09806602bfa.png)

I want to trim down to the data bounds of course. I'm using basemap over cartopy since it has the nice south polar stereo projection.

Data is from B-SOSE here: http://sose.ucsd.edu/BSOSE_iter105_solution.html if you want to give it a go.

**Comment by lukelbd** [comment]
No problem -- for this you just pass a `proj_kw` keyword-arg dictionary to [`subplots`](https://lukelbd.github.io/proplot/api/proplot.subplots.subplots.html). These keywords are passed to the initializers for `mpl_toolkits.basemap.Basemap` and `cartopy.crs.Projection` (and its various subclasses).

So in this case, you can use `plot.subplots(proj='spstere', basemap=True, proj_kw={'llcrnrlon':x, 'urcrnrlon':y, ...}`. Note that `subplots` internally uses the projection constructor function "[`Proj`](https://lukelbd.github.io/proplot/api/proplot.projs.Proj.html#proplot.projs.Proj)", which returns the basemap/cartopy class instance.

**Comment by lukelbd** [comment]
P.S. In a recent commit (e78c43d), I fixed the issues with "smart tight layout" and zoomed-in cartopy projections. There is actually a [cartopy github issue](https://github.com/SciTools/cartopy/issues/1207) with the solution posted, it just hasn't been implemented yet. "Smart tight layout" will now also fix issues associated with "zoomed in" cartopy projections having different aspect ratios than the intial aspect ratios, so you won't end up with a bunch of unnecessary empty space in your plot.

Anyway, now the only case when "smart tight layout" has to be disabled is when you use parallel/meridian labels with cartopy.

**Comment by bradyrx** [comment]
Thanks for all the tips, @lukelbd. I thought I had tried the `proj_kw` but maybe not. This is a pretty simple solution!

Good example you added to the docs. Maybe you should also add one to polar-specific projections. I'm just getting into Southern Ocean stuff so getting used to these keywords. Note that of course it doesn't use rectangular coordinates. You just pass `boundinglat` to set the extent.

```python
f, ax = plot.subplots(proj='spstere', basemap=True,
                      axwidth='10cm', 
                      proj_kw={'boundinglat': -30, 'lon_0': 120})
ax.pcolormesh(ds.XC, ds.YC, ds, vmin=-10, vmax=10,
              cmap='RdBu')
ax.format(land=True)
```
![Screen Shot 2019-05-20 at 9 17 14 AM](https://user-images.githubusercontent.com/8881170/58032560-167c0400-7ae0-11e9-97f9-5fef96789f49.png)
