### ISSUE TITLE
Error about xticklabel in geoaxes

### ISSUE THREAD

**Issue by heylsitan** [lukelbd/proplot#148]
### Description

I use labels=True in ax.format, although i set lonlim=(120,260), it return all the ticks along x axis. 

### Steps to reproduce

```python
f,axs=plot.subplots(axwidth=10,proj='cyl',proj_kw={'lon_0': 180})
ax=axs[0]


for i in range(lon2.shape[1]):
    longitude=lon2[:,i]
    latitude=lat2[:,i]
    h=p2[1:,i]
    
    points = np.array([longitude, latitude]).T.reshape(-1, 1, 2)
    segments = np.concatenate([points[:-1], points[1:]], axis=1)

    norm = plt.Normalize(100, 800)

    lc = LineCollection(segments, cmap=cmaps.MPL_jet, norm=norm,transform=ccrs.PlateCarree())        
    lc.set_array(h)

    line = ax.add_collection(lc)    

tick=[-0.5,0.5]
m=ax.contour(flag,levels=tick,color='red',zorder=20)

ax.scatter(LHx2,LHy2,marker='x')

ax.format(title='1979-01-04:00',fontsize=15, land=True, landcolor='gray',latlim=(15,80),lonlim=(120,260),labels=True)
ax.colorbar(line,loc='bottom',label='unit(hPa)')
```
![error](https://user-images.githubusercontent.com/6396737/81378606-24d08f00-913a-11ea-899b-ea1844c78edb.png)

**Expected behavior**: [What you expected to happen]
only show the xticklabels in the lonlim.
**Actual behavior**: [What actually happened]
show the ticklabels outside of the lonlim

### Equivalent steps in matplotlib

Please make sure this bug is related to a specific proplot feature. If you're not sure, try to replicate it with the [native matplotlib API](https://matplotlib.org/3.1.1/api/index.html). Matplotlib bugs belong on the [matplotlib github page](https://github.com/matplotlib/matplotlib).

```python
# your code here, if applicable
```

### Proplot version
0.50
Paste the result of `import proplot; print(proplot.version)` here.

**Comment by lukelbd** [comment]
This was a cartopy 0.17 bug. I've just added support for cartopy 0.18 in proplot (#158), so after the next version of proplot comes out (maybe a week), if you upgrade to cartopy 0.18 with e.g. `conda install -c conda-forge cartopy=0.18` it should be fixed.

Normally in matplotlib when you set an axis locator to [`FixedLocator`](https://matplotlib.org/3.2.1/api/ticker_api.html#matplotlib.ticker.FixedLocator) and the fixed tick locations extend outside of the axis bounds, matplotlib is supposed to not draw those ticks. However cartopy <=0.17 did not do this, so the `FixedLocator`s created by proplot and assigned to the axes would draw ticks outside of the map limits. In cartopy 0.18 this appears to have been fixed.
