### ISSUE TITLE
Native pcolor keywords overridden

### ISSUE THREAD

**Issue by bradyrx** [lukelbd/proplot#15]
It seems like some recent commits made native `pcolor` keywords funky. I'm zoomed in on the California coastline, so I like to use`pcolor` to keep things high-resolution and display the model grid resolution.

See `pcolor` doc ![here](https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.pcolor.html#matplotlib.axes.Axes.pcolor). I tend to call `ax.pcolor(lon, lat, data, edgecolors='w')` to display the grid with white lines.

```python
f, ax = plot.subplots(width='12cm', proj='cyl', basemap=False, tight=False)
ax.set_extent([-140, -110, 20, 50], crs=ccrs.PlateCarree())
ax.pcolor(data.TLONG, data.TLAT, data, edgecolors='w')
```

The above command used to produce something like this:

![Screen Shot 2019-03-28 at 4 43 32 PM](https://user-images.githubusercontent.com/8881170/55197582-a81e6380-5178-11e9-9f97-330febcaa5ae.png)

It now ignores the call for white edges and displays `pcolor` as if `edgecolors='face'`:

![Screen Shot 2019-03-28 at 4 44 54 PM](https://user-images.githubusercontent.com/8881170/55197695-e582f100-5178-11e9-9acf-9658af340890.png)

Now, if I call `ax.pcolor(data.TLONG, data.TLAT, data, edgecolors='w', linewidth=0.25)` it recognizes due to linewidth the desire for edge lines, although they remain black. (I tried changing `plot.rc['patch.edgecolor'] = 'w'` with no success.)

![Screen Shot 2019-03-28 at 4 46 41 PM](https://user-images.githubusercontent.com/8881170/55197775-20852480-5179-11e9-99bc-82fe46bda9ec.png)

Another weird thing to be aware of is that if I don't mention edgecolor, it renders a much sloppier looking edge line (`ax.pcolor(data.TLONG, data.TLAT, data, linewidth=0.25)`)

![Screen Shot 2019-03-28 at 4 48 16 PM](https://user-images.githubusercontent.com/8881170/55197810-4ad6e200-5179-11e9-8da7-c3f6af95ea0a.png)

**Comment by bradyrx** [comment]
@lukelbd, here's a sample netCDF for the masked California data: https://uploadfiles.io/j06y7

**Comment by lukelbd** [comment]
Ok, latest commit (2669bd6) should fix this. Now, if you pass any keyword arg that configures patch line/edge properties, the [`wrapper_cmap`](https://lukelbd.github.io/proplot/api/proplot.axes.wrapper_cmap.html#proplot.axes.wrapper_cmap) `fix=True` option is disabled, so it won't overwrite the keyword args you passed.

That weird zig-zag edge color may just be a [Moire pattern](https://en.wikipedia.org/wiki/Moir%C3%A9_pattern) associated with the rendering engine + that particular linewidth selection. Or some matplotlib bug.

**Comment by bradyrx** [comment]
Will test and confirm tomorrow. @lukelbd , thanks for naming that pattern. I get it a lot in paraview with high-resolution grids. Didn't know it had a name.
