### ISSUE TITLE
Show decimal places and scientific notation on the axis

### ISSUE THREAD

**Issue by zxdawn** [lukelbd/proplot#170]
### Description

When the number is large, matplotlib will use `e` notation automatically. But, we usually use `x10^{}` in science paper.

### Steps to reproduce

```python
import proplot as plot
import numpy as np

state = np.random.RandomState(51423)
fig, axs = plot.subplots()
axs.format(ylim=(0, 5e10), ylocator=2e10)
```

**Expected behavior**:
![scientific](https://user-images.githubusercontent.com/30388627/82120198-fcd6d080-97b6-11ea-96af-e4ddec8686ce.png)

**Actual behavior**:
![e](https://user-images.githubusercontent.com/30388627/82120209-137d2780-97b7-11ea-865c-f5fc7715fd88.png)

### Equivalent steps in matplotlib

```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker

fig, ax = plt.subplots()
x = np.linspace(0, 5e10, 4)
# y = x**2
ax.plot(x)

f = mticker.ScalarFormatter(useOffset=False, useMathText=True)
g = lambda x,pos : "${}$".format(f._formatSciNotation('%1.10e' % x))
plt.gca().yaxis.set_major_formatter(mticker.FuncFormatter(g))
```

### Proplot version
0.5.0

**Comment by lukelbd** [comment]
Neat idea! Yeah I agree your first example is way better. Will look into adding it to proplot's `AutoFormatter` (which is a subclass of `ScalarFormatter`)

**Comment by zxdawn** [comment]
BTW, you can find the detailed function of supporting custom digits on [stackoverflow](https://stackoverflow.com/questions/25750170/show-decimal-places-and-scientific-notation-on-the-axis-of-a-matplotlib-plot).
![image](https://user-images.githubusercontent.com/30388627/82133310-5a056d00-981d-11ea-8772-9f8c92b9b0f3.png)

**Comment by lukelbd** [comment]
I've added this feature, just need to submit a PR. Actually did two things:

(1) The new `AutoFormatter` always formats the exponent with math text, resulting in the following behavior (which is a step in the right direction):

![tmp](https://user-images.githubusercontent.com/19657652/82424576-9cf45a00-9a42-11ea-8747-330bf700b8a3.png)

(2) There is a new `SciFormatter` based on the stackoverflow link you posted (that poster is actually a core matplotlib developer). Results in the following behavior (the trailing zero-trimming behavior can be optionally disabled):

```python
import proplot as plot
fig, ax = plot.subplots()
ax.format(xlim=(-5, 5), ylim=(0, 1e20), yformatter='sci')
```

![tmp](https://user-images.githubusercontent.com/19657652/82430299-602c6100-9a4a-11ea-8225-330701660e89.png)

**Comment by zxdawn** [comment]
Thanks Luke! It works well.

Looking forward to the new version 0.6 ;)

**Comment by lukelbd** [comment]
Newest version is officially out :D

**Comment by zxdawn** [comment]
Wow, thanks! Totally switching to `proplot` now :D
