### ISSUE TITLE
Support of multipage pdf

### ISSUE THREAD

**Issue by lacstorm** [lukelbd/proplot#176]
### Description

Is Proplot currently support multipage pdf in matplotlib?

### Steps to reproduce

A "[Minimal, Complete and Verifiable Example](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)" will make it much easier for maintainers to help you.

```python
with PdfPages('WRF_hourly_prep_20190623.pdf') as pdf:
    for i in range(dim_tot[0]-1):
        fig, ax = plt.subplots(proj=cart_proj)

        ax[0].add_feature(provinces, linewidth=0.6)
        ax[0].coastlines('50m', linewidth=0.8)
    
        pcm = ax[0].contourf(lons, lats, h1prep[i], levels=levels, norm=norm,
                     transform=ccrs.PlateCarree(), extend='neither', cmap=cmaps.cmorph)

        ax[0].set_xlim(cartopy_xlim(rainc))
        ax[0].set_ylim(cartopy_ylim(rainc))  

        ax[0].set_title("WRF Prepcipitation {}".format(str(wrf_time[i],'utf-8')))
        #ax.gridlines(linewidth=0.5, color='gray', linestyle='--')
        gl = ax[0].gridlines(x_inline=False, draw_labels=True, linestyle='--',linewidth=0.5,color='dimgrey')
        gl.top_labels = False
        gl.right_labels = False
        # gl.xlines = False
        gl.xlocator = LongitudeLocator()
        gl.ylocator = LatitudeLocator()

        # plt.colorbar(pcm, ax=ax, ticks=levels, extendfrac='auto', 
        #              aspect=20, extendrect=True, format='%3.1f', drawedges=True, shrink=.7)
        ax[0].colorbar(pcm, ax=ax, ticks=levels, extendfrac='auto', 
                     aspect=18, format='%3.1f', shrink=.95)
        #plt.show()
        pdf.savefig()
```

**Expected behavior**: multipage pdf

**Actual behavior**: type error. Since the savefig method is redefined in proplot and can not use by pdfpages.

### Equivalent steps in matplotlib

Please make sure this bug is related to a specific proplot feature. If you're not sure, try to replicate it with the [native matplotlib API](https://matplotlib.org/3.1.1/api/index.html). Matplotlib bugs belong on the [matplotlib github page](https://github.com/matplotlib/matplotlib).

```python
# your code here, if applicable
```

### Proplot version

0.6.1

**Comment by lukelbd** [comment]
Sorry about that -- this was a two-line fix (426681d). You can use it by installing the development version of proplot with:

```
pip install git+https://github.com/lukelbd/proplot.git
```
