### ISSUE TITLE
Correct lon and lat labels for small region (cartopy)

### ISSUE THREAD

**Issue by zxdawn** [lukelbd/proplot#179]
### Description
When the region is small, the tick labels are not in the normal format: **.**N or **.**E

### Steps to reproduce
```python
import proplot as plot
extend = [118, 120, 31.5, 33.5]

f, axs = plot.subplots(ncols=2,
                       nrows=2,
                       proj='pcarree',
                       share=0
                       )
axs.format(
           abc=True, abcloc='ul', abcstyle='(a)',
           labels=True,
           lonlim=(extend[0], extend[1]),
           latlim=(extend[2], extend[3]),
           geogridlinewidth=0.5,
           geogridcolor='k',
           )
```

**Expected behavior**
![image](https://user-images.githubusercontent.com/30388627/83317836-68fb0f00-a262-11ea-84cf-ea11569e824d.png)

**Actual behavior**:
![image](https://user-images.githubusercontent.com/30388627/83317728-46b4c180-a261-11ea-8ec7-0b194bec5b1c.png)

### Equivalent steps in matplotlib
```python
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

extend = [118, 120, 31.5, 33.5]

proj = ccrs.PlateCarree()
fig, axs = plt.subplots(nrows=2, ncols=2,
                        subplot_kw={'projection': proj})

for idx,ax in enumerate(axs.flatten()):
    ax.set_extent(extend, ccrs.PlateCarree())
    gl = ax.gridlines(crs=ccrs.PlateCarree(), draw_labels=True,
                      color='gray', alpha=0.5, linestyle='--',
                      x_inline=False, y_inline=False)
```

### Proplot version
0.6.1

**Comment by lukelbd** [comment]
This is a feature. It's [documented on the website](https://proplot.readthedocs.io/en/latest/projections.html#Zooming-into-projections) but probably should have its own section. In general [degree-minute-second](https://en.wikipedia.org/wiki/Degree_(angle)#Subdivisions) are more appropriate for longitude-latitude coordinates, so I made this the default behavior.

You can switch back to decimal degrees using `ax.format(dms=False)`.
