### ISSUE TITLE
`savefig` broken with newest tight layout updates

### ISSUE THREAD

**Issue by bradyrx** [lukelbd/proplot#18]
`savefig` is currently broken with the most recent version of `proplot`.  Running `f.savefig('out.png')` returns:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-6-c73250c3d7b6> in <module>
      5 ax.format(land=True, landcolor='black', 
      6           suptitle='Zooming into Polar Stereographic Projections')
----> 7 f.savefig('test.png')

~/Desktop/proplot/proplot/subplots.py in savefig(self, filename, **kwargs)
    978         # Finally, save
    979         self._lock_twins()
--> 980         self._auto_bboxs(renderer)
    981         self._auto_title_pos() # just applies the spacing
    982         self._auto_smart_tight_layout()

NameError: name 'renderer' is not defined
```

This is because you added `self._auto_bboxs(renderer)` to `savefig` without adding `renderer` to the arguments. Might need a few tweaks here to fix it fully.

This could be caught in the future with some sort of testing. We've put together a reasonable `pytest` framework over at `climpred` (https://github.com/bradyrx/climpred/tree/master/climpred/tests) which is run with Travis CI for every PR. This catches some trivial errors like this for us. But I'm not sure how testing would work for a plotting library. A test could of course be implemented for saving figures.

**Comment by lukelbd** [comment]
Latest commits (fe37f28, 42e35ae) should fix this. Thanks for finding it.

You're totally right about `pytest` -- I think before releasing I will put together some tests. Thanks for the `climpred` example. Just saving each figure at the end of every test should be sufficient, since this does the same backend calculations/calls the same main functions as rendering the figure for interactive display.

**Comment by bradyrx** [comment]
Great, thank you. We've been combining two workflows at `climpred`, using `pytest` and `treon`. I think the latter would work best for your case here (you can see how we set it up in our Travis dotfile). But `treon` just tries to run your notebooks in your repo and fails if any of them don't execute properly. I could see you replicating your showcase in one big notebook (with lightweight examples) and a few savefigs here and there. Then `treon` would detect for you if there's any issues with new features. This of course has to be done with PRs.
