### ISSUE TITLE
Add the cite link or doi

### ISSUE THREAD

**Issue by zxdawn** [lukelbd/proplot#180]
I'm using `proplot` to plot all figures in my paper and want to cite this package to let more people know it.

If you can connect the github release with [zenodo](https://zenodo.org/), then we can cite it by doi.
That could be more suitable for research paper, instead of adding the github link at the end of manuscript.

**Comment by lukelbd** [comment]
Thanks for introducing me to zenodo and for asking to cite this project! I just added a new release (version 0.6.2) and [created a zenodo entry](https://zenodo.org/record/3873879), feel free to cite :)

**Comment by zxdawn** [comment]
Great! Will cite and recommend it to my friends ;)
