### ISSUE TITLE
Issue with autoformat for 2D plot with xarray

### ISSUE THREAD

**Issue by kinyatoride** [lukelbd/proplot#181]
### Description

Passing autoformat=False to subplots gives errors for 2D plot with xarray

### Steps to reproduce

```python
import xarray as xr
import numpy as np
import proplot as plot

da = xr.DataArray(
     np.array(
      [[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]]),
     dims=["x", "y"],
     coords={"x": [0, 1, 2, 4]})

fig, ax = plot.subplots(autoformat=False)

ax.contourf(da)
```

**Expected behavior**: [What you expected to happen]
Disable auto format

**Actual behavior**: [What actually happened]
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-3-a3cf3db361dc> in <module>
     39 fig, ax = plot.subplots(autoformat=False)
     40 
---> 41 ax.contourf(da)

~/miniconda3/envs/basic2/lib/python3.7/site-packages/proplot/ui.py in _iterator(*args, **kwargs)
    670                 result = []
    671                 for func in objs:
--> 672                     result.append(func(*args, **kwargs))
    673                 if len(self) == 1:
    674                     return result[0]

~/miniconda3/envs/basic2/lib/python3.7/site-packages/proplot/axes/plot.py in _wrapper(self, *args, **kwargs)
   3818         @functools.wraps(func)
   3819         def _wrapper(self, *args, **kwargs):
-> 3820             return driver(self, func, *args, **kwargs)
   3821         name = func.__name__
   3822         if name not in proplot_methods:

~/miniconda3/envs/basic2/lib/python3.7/site-packages/proplot/axes/plot.py in standardize_2d(self, func, order, globe, *args, **kwargs)
    868     # was stripped by globe=True.
    869     colorbar_kw = kwargs.pop('colorbar_kw', None) or {}
--> 870     colorbar_kw.setdefault('label', colorbar_label)
    871     return func(self, x, y, *Zs, colorbar_kw=colorbar_kw, **kwargs)
    872 

UnboundLocalError: local variable 'colorbar_label' referenced before assignment

### Equivalent steps in matplotlib

```python
import xarray as xr
import numpy as np
import matplotlib.pyplot as plt

da = xr.DataArray(
     np.array(
      [[ 0,  1,  2],
       [ 4,  4,  5],
       [ 6,  7,  8],
       [ 13, 10, 11]]),
     dims=["x", "y"],
     coords={"x": [0, 1, 2, 4]})

fig, ax = plt.subplots()

da.plot.contourf(ax=ax, add_labels=False)
```

### Proplot version
0.6.1

**Comment by lukelbd** [comment]
Thanks for the report! This was a very simple fix; it's in the master branch now.

**Comment by kinyatoride** [comment]
Great! Thanks for the quick turnaround.
