### ISSUE TITLE
Set extend automatically based on vmin and vmax

### ISSUE THREAD

**Issue by zxdawn** [lukelbd/proplot#185]
### Description
It would be more convenient to assign the `extend` based on `vmin` and `vmax`.

### Steps to reproduce

```python
import proplot as plot
import numpy as np
fig, axs = plot.subplots()
state = np.random.RandomState(51423)
m = axs.pcolormesh(
    state.rand(20, 20), cmap='viridis',
    vmax=0.5,
    # extend='max'
)

axs.colorbar(m)
```

**Expected behavior**:
The same result of adding `extend='max'`:
![image](https://user-images.githubusercontent.com/30388627/84389298-6a481680-ac28-11ea-827d-affc855aad25.png)

**Actual behavior**:
![image](https://user-images.githubusercontent.com/30388627/84389333-7502ab80-ac28-11ea-8613-bba6de5c3a82.png)

### Proplot version

0.6.3

**Comment by lukelbd** [comment]
I don't think I understand the rationale here. If users specify `vmin` or `vmax` it doesn't necessarily imply that they want to add `extend` colors beying those points (on the contrary it might mean these are rigid limits, so please don't color anything outside of this range). So for the sake of simplicity I don't think I will implement this.
