### ISSUE TITLE
colormap normalization.

### ISSUE THREAD

**Issue by lacstorm** [lukelbd/proplot#190]
[Description of the bug or feature.]
Error when using boudary normalization for colormap.
### Steps to reproduce

A "[Minimal, Complete and Verifiable Example](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)" will make it much easier for maintainers to help you.

```python
import matplotlib.pyplot as plt
import proplot as pplt
import numpy as np
import cmaps
import matplotlib.colors as colors
import matplotlib.ticker as ticker


state = np.random.RandomState(51423)
data = (state.rand(20, 20))*50
data[5:15,5:15] = 0.002
data[10:20,10:20] = 0.6
print(data.max(),data.min())

levels = [0.1,0.5,1.,2.,3.,4.,5.,6.,8.,10.,20.,40]
norm = colors.BoundaryNorm(boundaries=np.array(levels), ncolors=len(levels)-1)

# figure with proplot
fig, ax = pplt.subplots()
m0 = ax.contourf(data, levels=levels, extend='both', cmap=cmaps.cmorph,
colorbar="r",colorbar_kw={'ticks':levels})
ax.format(suptitle='plot with proplot')
fig.savefig('color_proplot.png')

# figure with matplotlib
fig, ax = plt.subplots()
m1 = ax.contourf(data, levels=levels, norm=norm, extend='both',cmap=cmaps.cmorph[1:])
m1.cmap.set_under(cmaps.cmorph.colors[0])
cb = plt.colorbar(m1, ax=ax, ticks=levels, extendfrac='auto', 
                     aspect=18, shrink=.95)

cb.ax.minorticks_off()

ax.set_title("plot with matplotlib")
fig.savefig('color_matplotlib.png')

# figure with proplot and boudary normalization
fig, ax = pplt.subplots()
m0 = ax.contourf(data, levels=levels, norm=norm, extend='both', cmap=cmaps.cmorph[1:],
colorbar="r",colorbar_kw={'ticks':levels})
m0.cmap.set_under(cmaps.cmorph.colors[0])

ax.format(suptitle='plot with proplot1')
fig.savefig('color_proplot1.png')

```

**Expected behavior**: [What you expected to happen]
![color_matplotlib](https://user-images.githubusercontent.com/35789946/84671800-608d1e80-af5a-11ea-86a6-55865724398b.png)

**Actual behavior**: [What actually happened]
### When using default segmented normalizaton in proplot:
![color_proplot](https://user-images.githubusercontent.com/35789946/84672079-b235a900-af5a-11ea-90a5-4728708705aa.png)

### And when using boudary normailiztion of matplotlib:
![color_proplot1](https://user-images.githubusercontent.com/35789946/84671939-887c8200-af5a-11ea-827c-e36712abe333.png)

### Equivalent steps in matplotlib

See the code above.

### Proplot version
0.6.1
Paste the result of `import proplot; print(proplot.version)` here.

**Comment by zxdawn** [comment]
@lacstorm It looks a little confused.

I would suggest you rewrite the example and state the problem in detail.
The example code should be a simple and minimal one.

1. The variables from `wrfout*` files can be replaced by numpy array
2. If the projection isn't necessary for this issue, you can just use Cartesian axis.
3. You can just attach the image by dragging that to the edit box

**Comment by lacstorm** [comment]
@zxdawn 
Hi xin.
Thanks, I'll test and submit a simple case later!

**Comment by zxdawn** [comment]
@lacstorm You're welcome. PS: you can edit the original one by clicking the dot button on the right corner ;)

**Comment by lacstorm** [comment]
@zxdawn 
Hi xin, I submit a very simple example.
Note that in the second figure, the colors for 20-40 and above 40 are the same.
And for the second plot, the colormap is the same with the first plot, but the contour is not right.

**Comment by lukelbd** [comment]
Hi @lacstorm,

I think this might have something to do with `BoundaryNorm`. Could you try without passing `norm=norm` to `contourf`? By default proplot automatically applies a "boundary norm" when the values in `levels` are unevenly spaced, so creating your own boundary norm is usually not necessary (see [this section](https://proplot.readthedocs.io/en/latest/2dplots.html#Special-normalizers) from the docs).

I also noticed you used `set_under` but did not user `set_over`. Adding `m1.cmap.set_over(cmaps.cmorph.colors[-1])` might give you the desired result.

Also I can't reproduce the example because I think `cmaps` is a local module on your system. You could share it by uploading it to `file.io` or posting a google drive link.

**Comment by lukelbd** [comment]
Nevermind re: that first suggestion -- I see you already tried that.

Adding `set_over(cmap.cmorph.colors[-1])` still might fix your problem. And I think this will also require using `cmaps.cmorph[1:-1]` instead of `cmaps.cmorph[1:]`. For example:

```python
cmap = plot.Colormap(cmaps.cmorph[1:-1])
cmap.set_under(cmaps.cmorph[0])
cmap.set_over(cmaps.cmorph[-1])
ax.contourf(..., cmap=cmap)
```

**Comment by lukelbd** [comment]
To be clear, what is `cmaps.cmorph`? Is that a list of colors?

**Comment by lacstorm** [comment]
@lukelbd 
Hi luke. I tried to do this like this:
(I tried to use only norm=norm or levels=levels, still ain't right.)
``` python
# figure with proplot and boudary normalization
fig1, ax1 = pplt.subplots()
m2 = ax1.contourf(data, levels=levels, norm=norm, extend='both', cmap=cmaps.cmorph[1:-1],
colorbar="r",colorbar_kw={'ticks':levels})
m2.cmap.set_under(cmaps.cmorph.colors[0])
m2.cmap.set_over(cmaps.cmorph.colors[-1])

ax1.format(suptitle='plot with proplot2')
fig1.savefig('color_proplot1.png')
```
**And I still got the same result with "plot with proplot1":**
![color_proplot1 2](https://user-images.githubusercontent.com/35789946/84712836-32303300-af9c-11ea-9777-cf93cf3b15e4.png)

**Please note that the cmap.set_under is not working, values below 0.1 is contoured by cmaps.cmorph.colors[1].**
cmaps is a package to transfer ncl or self_defined colormap to python, and could be found [here](https://github.com/hhuangwx/cmaps).
The cmorph is a self-defined colormap, which is a list of 13 colors:
```
ncolors= 13
#  r   g   b
 255 255 255
   0 225 225
   0 165 185
   0 185   0
   0 255  45
 255 255   0
 225 205   0
 160 120   0
 160  40   0
 185   0   0
 255   0 155
 185   0 255
 125   0 255
```

**Comment by lukelbd** [comment]
Sorry I couldn't get to this sooner, but I finally figured it out (see https://github.com/lukelbd/proplot/commit/f23ff70d54ffa668212e65c1d80ede3a310f5518). This was actually two separate bugs:

* `plot.Colormap()` automatically translates native matplotlib colormaps to proplot's special colormap subclasses `plot.colors.LinearSegmentedColormap` and `plot.colors.ListedColormap`. However when doing this, proplot failed to copy the "extreme" color values.
* `plot.DiscreteNorm()` failed to account for the possibility that there is a *discrete transition* between the minimum/maximum colors "within" the colormap range (colormap coordinates `0` and `1`) and the out of bounds colors (coordianates `0 - eps` and `1 + eps`). Now it takes this into account.

Here's your example on master:

```python
import matplotlib.pyplot as plt
import proplot as pplt
import numpy as np
import matplotlib.colors as colors
import matplotlib.ticker as ticker


state = np.random.RandomState(51423)
data = (state.rand(20, 20))*50
data[5:15,5:15] = 0.002
data[10:20,10:20] = 0.6
#print(data.max(),data.min())

# define colormap
cmorph = [[255.,255,255],
   [0,225,225],
   [0,165,185],
   [0,185, 0],
   [0 ,255 , 45],
 [255, 255 ,  0],
 [225 ,205 ,  0],
 [160, 120 ,  0],
 [160 , 40 ,  0],
 [185 ,  0 ,  0],
 [255  , 0 ,155],
 [185  , 0 ,255],
 [125 ,  0, 255]]

cmorph = np.array(cmorph) / 255.0
cmap0 = colors.ListedColormap(cmorph[1:-1])
cmap0.set_under(cmorph[0])
cmap0.set_over(cmorph[-1])
levels = [0.1,0.5,1.,2.,3.,4.,5.,6.,8.,10.,20.,40]

# Figure with proplot
fig, ax = pplt.subplots()
m0 = ax.contourf(
  data, levels=levels, extend='both', cmap=cmap0,
  colorbar='b', colorbar_kw={'ticks':levels}
)

ax.format(suptitle='plot with proplot')
```

![tmp](https://user-images.githubusercontent.com/19657652/85237517-d07d2800-b3e4-11ea-956b-dfda70c86af7.png)

**Comment by lacstorm** [comment]
@lukelbd 
Hi, luke. It's ok now.
Thanks for developing such an effective package!
