### ISSUE TITLE
issue with ax.fill in geographic plots

### ISSUE THREAD

**Issue by kinyatoride** [lukelbd/proplot#193]
### Description

ax.fill in geographic plots seem to have some issues.

### Steps to reproduce

```python
import proplot as plot

fig, ax = plot.subplots(proj='cyl', proj_kw={'lon_0': 180})
ax.format(coast=True, labels=True)
ax.fill([0, 100, 100, 0], [0, 0, 50, 50], fill=False)
```

**Expected behavior**: [What you expected to happen]
![Screen Shot 2020-06-16 at 17 20 05](https://user-images.githubusercontent.com/61028484/84840873-a0551400-aff5-11ea-97b9-7492402bab9d.png)

**Actual behavior**: [What actually happened]
![Screen Shot 2020-06-16 at 17 20 28](https://user-images.githubusercontent.com/61028484/84840891-ae0a9980-aff5-11ea-9362-81fecd3d6536.png)

It works fine when combined with cartopy

```python
import cartopy.crs as ccrs
fig, ax = plot.subplots(proj='cyl', proj_kw={'lon_0': 180})
ax.format(coast=True, labels=True)
ax.fill([0, 100, 100, 0], [0, 0, 50, 50], fill=False, transform=ccrs.PlateCarree())
```

### Proplot version

0.6.4

**Comment by lukelbd** [comment]
This is because `GeoAxes.fill` was not wrapped by proplot, so it required `transform=ccrs.PlateCarree()`.   010773c makes `transform=ccrs.PlateCarree()` the default like in other proplot contexts.
