### ISSUE TITLE
indicate_error for x direction

### ISSUE THREAD

**Issue by kinyatoride** [lukelbd/proplot#194]
### Description

It would be really nice if `indicate_error` can also show error bars in x direction. 

### Steps to reproduce

```python
import numpy as np
import proplot as plot

x = np.arange(10)
rng = np.random.default_rng()
y = rng.standard_normal((100, 10))

fig, ax = plot.subplots()
ax.plot(y, x, means=True)
```

### Equivalent steps in matplotlib

`errorbar` has the `xerr` option to do this

**Comment by lukelbd** [comment]
Added this as part of a giant refactor. Here's a screenshot of the new website example showcasing this (should appear soon).

<img width="433" alt="Screen Shot 2021-07-11 at 2 53 30 AM" src="https://user-images.githubusercontent.com/19657652/125188969-2f316180-e1f3-11eb-8050-976c60ca7655.png">

**Comment by lukelbd** [comment]
I went about this by adding `plotx` and `scatter` commands, analogous to `fill_betweenx`, `hlines`, and `barh`, that use the *y* axis as the dependent variable and take input arguments as follows: `ax.plotx(y)` or `ax.plotx(y, x)`. Had been meaning to do this anyway! The website now showcases these commands under the "1D plotting" section.
