### ISSUE TITLE
labels of pandas dataframe in histogram plot

### ISSUE THREAD

**Issue by kinyatoride** [lukelbd/proplot#195]
### Description

When pandas dataframe is passed to `hist`, the labels are shown in x axis. Can we put them to legend labels instead?

### Steps to reproduce

```python
import numpy as np
import pandas as pd
import proplot as plot

rng = np.random.default_rng()
x = rng.standard_normal((500, 2))
x = pd.DataFrame(x, columns=['a', 'b'])

fig, ax = plot.subplots()
ax.hist(x)

plot.show()
```

**Expected behavior**: [What you expected to happen]
Show actual x values, rather than showing labels in x axis.

**Actual behavior**: [What actually happened]
![Screen Shot 2020-06-18 at 18 07 40](https://user-images.githubusercontent.com/61028484/85086114-9c102e80-b18e-11ea-9c10-4b3d7cd304fb.png)

### Equivalent steps in matplotlib

```python
import numpy as np
import matplotlib.pyplot as plt

rng = np.random.default_rng()
x = rng.standard_normal((500, 2))
x = pd.DataFrame(x, columns=['a', 'b'])

fig, ax = plt.subplots()
ax.hist(x['a'], label='a')
ax.hist(x['b'], label='b')
ax.legend()
plt.show()
```
![Screen Shot 2020-06-18 at 18 08 27](https://user-images.githubusercontent.com/61028484/85086178-b6e2a300-b18e-11ea-8b93-3d4e3909cdb3.png)

### Proplot version

0.6.4

**Comment by lukelbd** [comment]
Fixed by https://github.com/lukelbd/proplot/commit/b5c3ec4c13a769331f70d9776f45d03b147a2951:

```python
import numpy as np
import pandas as pd
import proplot as plot

rng = np.random.default_rng()
x = rng.standard_normal((500, 2))
x = pd.DataFrame(x, columns=['a', 'b'])
bins = np.linspace(-4, 4, 17)

fig, ax = plot.subplots()
ax.hist(x, bins, legend=True, alpha=0.5)
ax.format(suptitle='Histogram example')
```

![tmp](https://user-images.githubusercontent.com/19657652/85185522-7b5cdd00-b251-11ea-9846-ee3fc83aaad3.png)
