### ISSUE TITLE
eps figures save massive object outside of figure

### ISSUE THREAD

**Issue by bradyrx** [lukelbd/proplot#20]
Not really sure how to debug this, but something in your figure saving creates vector objects that extend to seemingly infinity off the screen. 

You can see here in my illustrator screenshot. The bar object can't be modified by illustrator really because it says transforming it will make it too large. The blue outline seen extends downward infinitely. If I save an eps from `matplotlib` the object is only the size of the bar.

<img width="1366" alt="Screen Shot 2019-06-12 at 11 25 21 AM" src="https://user-images.githubusercontent.com/8881170/59372567-0b924900-8d05-11e9-97c6-d32a6b434adc.png">

**Comment by bradyrx** [comment]
This more accurately depicts what's being rendered:

<img width="1463" alt="Screen Shot 2019-06-12 at 11 33 15 AM" src="https://user-images.githubusercontent.com/8881170/59372980-e8b46480-8d05-11e9-974f-4dccba4eefac.png">

**Comment by lukelbd** [comment]
Yikes. I guess for some reason with proplot it tries to render the entire object from "zero" to the top of the bar... and since it's a logarithmic axis zero is negative infinity. Will look into this.

**Comment by lukelbd** [comment]
Which app were you using to view the `eps`? Want to try to reproduce this

**Comment by lukelbd** [comment]
@bradyrx Haven't been able to reproduce this, and it looks more like a matplotlib bug than a proplot bug to me. But feel free to reopen if you run into this problem again
