### ISSUE TITLE
Support enabling the footage of script location and datetime

### ISSUE THREAD

**Issue by zxdawn** [lukelbd/proplot#207]
### Description

I came across this [twitter](https://twitter.com/mattkenworthy/status/1282647041085079552?s=20) which shows that it would be helpful to embed the info of script and datetime into the figure:
![image](https://user-images.githubusercontent.com/30388627/87387332-12108580-c5d5-11ea-9efc-77d9f21c71d6.png)

If you agree, I suppose it would be better to plot these texts **below** the main figure, instead of the corner.
### Proplot version

0.6.4

**Comment by lukelbd** [comment]
Neat idea but this also seems a little niche (and people put all sorts of stamps and taglines on their figures; if I implement this I'd probably have to start supporting lots of different options). Don't think I will implement this.
