### ISSUE TITLE
Longitude labels over 180° are not plotted in cartopy v0.17

### ISSUE THREAD

**Issue by floatlikecloud** [lukelbd/proplot#208]
### Description
For longitude over 180°, longitude labels are not shown and grid lines are not plotted correctly. This issue only appears in v0.6 but not in v0.5. 

### Steps to reproduce

```python
import proplot as plot
# the cartopy version used is 0.17.0

f, axs = plot.subplots(proj='cyl', proj_kw={'lon_0':120})
axs.format(coast=True, latlines=30, lonlines=60, labels=True)
```

**Expected behavior (in v0.5.0)**: 
![map_v0 5 0](https://user-images.githubusercontent.com/43595995/87453346-96f0a480-c5bf-11ea-8bd6-403cfa975945.png)

**Actual behavior (in v0.6.4)**:
![map_v0 6 4](https://user-images.githubusercontent.com/43595995/87453356-9b1cc200-c5bf-11ea-884e-0eff0447689e.png)

### Proplot version
0.6.4

**Comment by lukelbd** [comment]
Thanks for the report. For now you can fix this bug simply by upgrading to cartopy 0.18. The cartopy grid labelling API changed a ton from 0.17 --> 0.18 -- I tried to make proplot's updates backwards-compatible with older cartopy versions but evidently missed this edge case.

**Comment by lukelbd** [comment]
Welp 1.5 years later... I found the solution. Not too important since none of the newer cartopy versions have this problem, but maybe it will help a new proplot user with an older version of cartopy. And I can finally close this :)
