### ISSUE TITLE
Adjust limits of colorbar automatically based on the data cropped by xlim and ylim

### ISSUE THREAD

**Issue by zxdawn** [lukelbd/proplot#209]
### Description

The value limits of colorbar are based on the whole input data.

But, we sometimes set the `xlim` or `ylim`.
Then, the colorbar limits should be changed accordingly.

### Steps to reproduce

```python
import proplot as plot
import numpy as np

fig, axs = plot.subplots(ncols=2, axwidth=2, share=0)
state = np.random.RandomState(51423)
data = (state.normal(0, 1, size=(33, 33))).cumsum(axis=0).cumsum(axis=1)

axs.format(suptitle='not adjusted')

axs[0].pcolor(data, cmap='spectral_r', N=10, colorbar='r')
axs[0].format(title='no_limit')

m = axs[1].pcolor(data, cmap='spectral_r', N=10, colorbar='r')
axs[1].format(ylim=[15, 25], title='ylimit [15 ,25]')
```

**Expected behavior**: [What you expected to happen]
Like the manually corrected colorbar limits:

```
import proplot as plot
import numpy as np

fig, axs = plot.subplots(ncols=2, axwidth=2, share=0)
state = np.random.RandomState(51423)
data = (state.normal(0, 1, size=(33, 33))).cumsum(axis=0).cumsum(axis=1)

axs.format(suptitle='manually adjusted')

axs[0].pcolor(data, cmap='spectral_r', N=10, colorbar='r')
axs[0].format(title='no_limit')

m = axs[1].pcolor(data, cmap='spectral_r', vmax=8, N=10, colorbar='r')
axs[1].format(ylim=[15, 25], title='ylimit [15 ,25]')
```

![test_clb_limit_manual](https://user-images.githubusercontent.com/30388627/87676263-f65ed800-c7aa-11ea-954d-9ee2d77d202e.png)

**Actual behavior**:

![test_clb_limit](https://user-images.githubusercontent.com/30388627/87676272-f959c880-c7aa-11ea-8135-4270ab899325.png)

### Proplot version

0.6.4

**Comment by lukelbd** [comment]
Love this idea -- I run into this problem a lot! In my plotting code I just crop the data itself to one pixel outside the `xlim` and `ylim` ranges. Adding it to the to-do list.

**Comment by lukelbd** [comment]
I decided to implement this since this has always bothered me (482f7e2). Turned out to be relatively simple -- the only caveat is that you must set the limits before you call the plotting command. Don't think there's a way to get around that restriction.

Here's an example of the new behavior:

```python
import proplot as plot
import numpy as np

fig, axs = plot.subplots(ncols=2, axwidth=2, share=0)
state = np.random.RandomState(51423)
data = (state.normal(0, 1, size=(33, 33))).cumsum(axis=0).cumsum(axis=1)
axs[0].format(title='Auto limits')
axs[0].pcolor(data, cmap='spectral_r', N=10, colorbar='r')
axs[1].format(ylim=(15, 25), title='Manual limits')
axs[1].pcolor(data, cmap='spectral_r', N=10, colorbar='r')
```

![tmp](https://user-images.githubusercontent.com/19657652/125215875-d35deb80-e279-11eb-8db5-f8b799d79d69.png)

**Comment by zxdawn** [comment]
Ha, thanks a lot. Nice trick!
