### ISSUE TITLE
Figure size/aspect for projections is not working anymore with the last version of Matplotlib

### ISSUE THREAD

**Issue by mickaellalande** [lukelbd/proplot#210]
### Description

I was trying to make a new environment with updated packages, but I faced a colorbar **extend** warning with the new version but the biggest problem is the size/aspects of the figures that are not good anymore for projections. I think it is coming from the last version of **Matplotlib 3.3**. Here is the problem with a random example:

### Steps to reproduce

```python
import proplot as plot
import xarray as xr

da = xr.tutorial.open_dataset('air_temperature').air - 273.15
clim = da.groupby(da['time.season']).mean('time')

f, axs = plot.subplots(proj='cyl', ncols=2, nrows=2)

for i, ax in enumerate(axs):
    m = ax.contourf(clim.isel(season=i), levels=plot.arange(-30,30,5), extend='both', cmap='CoolWarm')
    
    ax.format(
        labels = True, coast = True, borders = True, lonlines=30, latlines=15, 
        latlim=(clim.lat.min().values, clim.lat.max().values),  
        lonlim=(clim.lon.min().values, clim.lon.max().values),
        title=clim.isel(season=i).season.values
    )
    
f.colorbar(m, label='Near-Surface Air Temperature [°C]')
```

> /data/mlalande/miniconda3/envs/phd_v2/lib/python3.8/site-packages/proplot/figure.py:1158: MatplotlibDeprecationWarning: The 'extend' parameter to Colorbar has no effect because it is overridden by the mappable; it is deprecated since 3.3 and will be removed two minor releases later.
>   return super().colorbar(*args, cax=cax, **kwargs)

**Actual behavior**:
![extend_phd_v2](https://user-images.githubusercontent.com/20254164/87948830-80f25080-caa5-11ea-9cf1-75f9df93afc8.jpg)

**Expected behavior**
And with my previous environment I was having this:
![extend_work](https://user-images.githubusercontent.com/20254164/87948935-a41d0000-caa5-11ea-8d9d-60e871a8f5cd.jpg)

### Proplot version

I passed from: ([work.txt](https://github.com/lukelbd/proplot/files/4948286/work.txt))
- proplot 0.5.0 
- matplotlib 3.1.3

to: ([phd_v2.txt](https://github.com/lukelbd/proplot/files/4948288/phd_v2.txt))
- proplot 0.6.4
- matplotlib 3.3.0

I tried to downgrade matplotlib to 3.2, it actually does solve the problem but I still have another issue with the colorbar extend that doesn't work in certain cases (I didn't succeed to reproduce with a simple example...).

**Comment by lukelbd** [comment]
This is not pretty... will try to address it in the next few days.

**Comment by lukelbd** [comment]
Solution was simpler than I thought -- see #235
