### ISSUE TITLE
Issue with positions arguments in boxplot/violinplot when xarray is passed

### ISSUE THREAD

**Issue by kinyatoride** [lukelbd/proplot#214]
### Description

xticks contain meta information and cannot be changed when xarray is passed to `boxplot` or `violinplot`

### Steps to reproduce

```python
import xarray as xr
import numpy as np
import proplot as plot

rng = np.random.default_rng()

da = xr.DataArray(
     rng.standard_normal((500, 2)),
     dims=['sample', 'x'],
     coords={'x': ['a', 'b']})

fig, ax = plot.subplots()
ax.boxplot(da)

#ax.boxplot(da, positions=['a', 'b'])   # cannot change with this either
```

**Expected behavior**: [What you expected to happen]
![test2](https://user-images.githubusercontent.com/61028484/89233963-adc35f00-d59f-11ea-97a9-603cf2e3485f.png)

**Actual behavior**: [What actually happened]
![test1](https://user-images.githubusercontent.com/61028484/89233968-b0be4f80-d59f-11ea-9db9-9f5006c519c5.png)

### Proplot version

0.6.4

**Comment by lukelbd** [comment]
Thanks for finding this -- b95fe2c fixes it.
