### ISSUE TITLE
xminorlocator=1 or yminorlocator=1 doesn't work

### ISSUE THREAD

**Issue by mickaellalande** [lukelbd/proplot#219]
I think this line creates a problem when we define `yminorlocator=1` or `xminorlocator=1`: 
https://github.com/lukelbd/proplot/blob/e1a603729305abe791ed23d84cfeff11e5a4cea6/proplot/axes/cartesian.py#L1101

### Example 
```python
import proplot as plot
import numpy as np

fig, ax = plot.subplots(aspect=4, axwidth=5)

ax.format(
    xlim=(0, 200), xminorlocator=10, xlocator=30,
    ylim=(0, 4), yminorlocator=1, ylocator=2
)
```

Raise the warning:
```python
proplot/axes/cartesian.py:1102: ProPlotWarning: You passed yminorticks=1, but this argument is used to specify 
tick *locations*. If you just want to *toggle* minor ticks on and off, please use ytickminor=True or 
ytickminor=False.
```

A way to fix this is to pass `minorlocator=1.000001` for example, I guess the problem is that in Python `1` is equivalent to `True`.

### Proplot version
0.6.4

**Comment by lukelbd** [comment]
Thanks! One-line fix: a5d0c44
