### ISSUE TITLE
Proplot in jupyterlab generate continuous cpu usage

### ISSUE THREAD

**Issue by ghislainp** [lukelbd/proplot#222]
### Description

Proplot plots make busy jupyterlab all the time.

### Steps to reproduce

A "[Minimal, Complete and Verifiable Example](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)" will make it much easier for maintainers to help you.

```python
import proplot as pp
%matplotlib widget

f, axs = pp.subplots()

axs.plot([1, 5], [6, 7])
```

**Expected behavior**: Once plotted, jupyterlab should return to "idle" mode (when the mouse is not moving)

**Actual behavior**: Once plotted, jupyterlab switches between idle and busy very rapidly and loads the CPU.

### Equivalent steps in matplotlib

Please make sure this bug is related to a specific proplot feature. If you're not sure, try to replicate it with the [native matplotlib API](https://matplotlib.org/3.1.1/api/index.html). Matplotlib bugs belong on the [matplotlib github page](https://github.com/matplotlib/matplotlib).

```python
import matplotlib.pyplot as plt
%matplotlib widget

plt.plot([1, 5], [6, 7])
```

### Proplot version

Proplot: 0.6.1
Matplotlib: 3.3.1
jupyterlab: 2.2.6
ipympl: 0.5.7

**Comment by lukelbd** [comment]
Hi, this is probably related to #76. The problem proplot has with these interactive backends is it has a complicated geometry/layout algorithm that tries to update subplot positions and figure sizes automatically.

I added support for `%matplotlib notebook` backend by (necessarily) disabling auto figure resizing, but after an hour of trying I couldn't get `ipympl` installed on my machine. However I think 38290e7 might solve the issue -- try out the development branch with `pip install git+https://github.com/lukelbd/proplot.git` if you're still interested.
