### ISSUE TITLE
Can not share axis between a coutourf and a plot.

### ISSUE THREAD

**Issue by lacstorm** [lukelbd/proplot#223]
### Description

When you use twinx() to share axis of a "ax.contourf" and  a "ax.plot", there will be no lines of the "ax.plot".

### Steps to reproduce

A "[Minimal, Complete and Verifiable Example](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)" will make it much easier for maintainers to help you.

```python
import proplot as plot
import numpy as np
N = 20
state = np.random.RandomState(51423)
data = 10 ** (0.25 * np.cumsum(state.rand(N, N), axis=0))
fig, ax = plot.subplots()
ax.format(
    xlabel='xlabel', ylabel='ylabel', grid=True,
)
ax.contourf(data, cmap='bwr', colorbar='b')
ay = ax.twinx()
ay.plot(range(20),np.linspace(1,20,20),zorder=10)
```

**Expected behavior**: [What you expected to happen]

**Actual behavior**: [What actually happened]

![image](https://user-images.githubusercontent.com/35789946/91285267-943cbe00-e7bf-11ea-8508-e1fdeca6c15f.png)

### Proplot version
0.6.4

**Comment by lukelbd** [comment]
Thanks @lacstorm -- this was simple to fix (see 6ff4bb0).
