### ISSUE TITLE
get_legend() on ax object returns NoneType

### ISSUE THREAD

**Issue by AnGWar26** [lukelbd/proplot#224]
### Description

When calling `get_legend` on a `proplot` ax object, a `NoneType` is returned instead of the legend. This stops a user from modifying the legend after it's created, such as when using the `pandas` or `geopandas` plotter.

### Steps to reproduce

```python
import pandas as pd
import proplot as plot
import numpy as np
state = np.random.RandomState(51423)
data = 2 * (state.rand(100, 5) - 0.5).cumsum(axis=0)
data= pd.DataFrame(data)
fig, ax = plot.subplots()
data.plot(ax=ax,lw=2,legend=True)
print(type(ax.get_legend()))
```
![Screenshot from 2020-08-31 11-04-51](https://user-images.githubusercontent.com/64164151/91751577-85d21600-ebb4-11ea-8aea-be06ff6266a8.png)

**Expected behavior**: For the type of ax.get_legend to be a matplotlib or proplot legend object.

**Actual behavior**: The result of `ax.get_legend` is of `NoneType`.

### Equivalent steps in matplotlib

```python
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
state = np.random.RandomState(51423)
data = 2 * (state.rand(100, 5) - 0.5).cumsum(axis=0)
data= pd.DataFrame(data)
fig, ax = plt.subplots()
data.plot(ax=ax, lw=2,legend=True)
print(type(ax.get_legend()))
```

![Screenshot from 2020-08-31 11-05-25](https://user-images.githubusercontent.com/64164151/91751627-997d7c80-ebb4-11ea-8dcb-8fce4b750b5b.png)

This code returns `<class 'matplotlib.legend.Legend'>` as is expected.

### Proplot version
0.6.4

**Comment by lukelbd** [comment]
Thanks @AnGWar26. Proplot bypasses matplotlib's `Axes.legend()` to permit more than one legend in a subplot, but that also means making legends invisible to `get_legend()`. Now, the first legend drawn in the figure is accessible with `get_legend()`.
