### ISSUE TITLE
Dual axis doesn't change based on the original ticks

### ISSUE THREAD

**Issue by zxdawn** [lukelbd/proplot#228]
### Description

Dual axes work well when the ticks are set by default.
However, when we assign the ticks, the dual-axis doesn't change.

### Steps to reproduce

```python
import proplot as plot
f, ax = plot.subplots()
ax.format(xlim=(1,1000), xticks=500)
ax.dualx(lambda x: x/2)
```

**Expected behavior**:
Dual axis shows just two values: 250 and 500.

**Actual behavior**:
![test_dual](https://user-images.githubusercontent.com/30388627/94823932-0182e500-0437-11eb-8b74-dd9242d8b1c1.png)

And, the log axis has the same problem:
```
import proplot as plot
f, ax = plot.subplots()
ax.format(xlim=(1,1000), xticks=500, xscale='log')
ax.dualx(lambda x: x/2)
```

![test_dual](https://user-images.githubusercontent.com/30388627/94824019-20817700-0437-11eb-82d4-b764b7b0322c.png)

### Proplot version

0.6.4

**Comment by lukelbd** [comment]
Going to go with "it's not a bug, it's a feature" on this one. Users won't always want matching ticklines/gridlines on dual axes, and for non-linear "dual" transforms (e.g. `'inverse'`) this approach doesn't make sense.

So the current behavior is fine I think: when a "dual" axis is created, it starts out with the default `AutoLocator` just like any other axis, but users can change tick locations if they want.

In your example you can use `ax.dualx(lambda x: x / 2, xticks=250)`.
