### ISSUE TITLE
Please incorporate urban areas in ax.format(urban=True)

### ISSUE THREAD

**Issue by pratiman-91** [lukelbd/proplot#230]
### Description

It would be great if you can add urban area (https://www.naturalearthdata.com/downloads/50m-cultural-vectors/50m-urban-areas/) in the ax.format(urban=True).

### Steps to reproduce

```python
import proplot as plot
fig, axs = plot.subplots(nrows=2, axwidth=3, proj='robin', proj_kw={'lon_0': 180})
axs.format(
    suptitle='Figure with single projection',
    coast=True, urban=True, latlines=30, lonlines=60,
)
```

**Expected behaviour**: [What you expected to happen]
![test1](https://user-images.githubusercontent.com/31694629/97070960-2ca5c200-15fa-11eb-9850-b613fa524749.png)

**Actual behaviour**: [What actually happened]
![test](https://user-images.githubusercontent.com/31694629/97070956-2283c380-15fa-11eb-966d-cebc2486feab.png)

### Equivalent steps in matplotlib

Please make sure this bug is related to a specific proplot feature. If you're not sure, try to replicate it with the [native matplotlib API](https://matplotlib.org/3.1.1/api/index.html). Matplotlib bugs belong on the [matplotlib github page](https://github.com/matplotlib/matplotlib).

```python
import proplot as plot
from cartopy.feature import NaturalEarthFeature
urban = NaturalEarthFeature(category="cultural", scale="10m",
                             facecolor="none",
                             name="urban_areas")
fig, axs = plot.subplots(nrows=2, axwidth=3, proj='robin', proj_kw={'lon_0': 180})
axs.format(
    suptitle='Figure with single projection',
    coast=True, latlines=30, lonlines=60,
)
axs.add_feature(urban, linewidth=1.5, edgecolor="blue")
```

### Proplot version

0.6.4

**Comment by lukelbd** [comment]
Sorry I think this is a little too specialized. I think it's reasonable for proplot to support only the most common features like coasts and land masses, but ask users to use `cartopy.feature` for the less common ones. Cartopy does something similar with e.g. `cartopy.mpl.geoaxes.GeoAxes.coastlines()` and `cartopy.feature.COASTLINES` (see [this page](https://scitools.org.uk/cartopy/docs/v0.16/matplotlib/feature_interface.html) for details). If I start supporting natural earth features beyond these basic ones, that opens a whole can of worms.
