### ISSUE TITLE
large spaces between rows in plot with geo subplots

### ISSUE THREAD

**Issue by sjvg** [lukelbd/proplot#247]
### Description

Hello, when I do a simple geographical plot with suplots, like one of those in the readthe docs, I obtain subplot with large space between rows. Something that never happened before. How do I do to remove it?
Many thanks for your help.

### Steps to reproduce

```python
import proplot as plot
fig, axs = plot.subplots(nrows=2, axwidth=3, proj='robin', proj_kw={'lon_0': 180})
axs.format(
    suptitle='Figure with single projection',
    coast=True, latlines=30, lonlines=60,
)
```

**Expected behavior**: [What you expected to happen]
![Screenshot from 2021-03-04 16-07-46](https://user-images.githubusercontent.com/19325460/109984157-cb0e0680-7d03-11eb-822c-5a9c73f76ff4.png)

**Actual behavior**: [What actually happened]
![Screenshot from 2021-03-04 16-05-55](https://user-images.githubusercontent.com/19325460/109984076-b92c6380-7d03-11eb-9690-9bc0723dec9e.png)

```python
# your code here, if applicable
```

### Proplot version
proplot                   0.6.4
python                    3.6.13
matplotlib-base           3.3.4

**Comment by sjvg** [comment]
switching back to matplotlib-base-3.2.2, resolves the issue.

**Comment by lukelbd** [comment]
Duplicate of: #210. Will address this soon
