### ISSUE TITLE
Boxplot with different lengths of arrays

### ISSUE THREAD

**Issue by kinyatoride** [lukelbd/proplot#256]
### Description
Hi Luke, glad that you came back!
There is an error when a list consist of different lengths of arrays is passed to `boxplot`. This does not happen with `matplotlib`. It would be great if you can fix this! Thank you.

### Steps to reproduce

```python
import numpy as np
import proplot as plot

rng = np.random.default_rng()

x = np.array([rng.standard_normal(10), 
              rng.standard_normal(20), 
              rng.standard_normal(30)],
             dtype='object')

fig, ax = plot.subplots()
ax.boxplot(x)
```

**Expected behavior**: [What you expected to happen]
This is the matplotlib output.
![Screen Shot 2021-07-06 at 13 37 49](https://user-images.githubusercontent.com/61028484/124664231-fe9ea000-de5f-11eb-9e88-fce39eefa3de.png)

**Actual behavior**: [What actually happened]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-bb3bdce988e9> in <module>
     11 
     12 fig, ax = plot.subplots()
---> 13 ax.boxplot(x)

~/miniconda3/envs/basicf/lib/python3.8/site-packages/proplot/ui.py in _iterator(*args, **kwargs)
    680                 result = []
    681                 for func in objs:
--> 682                     result.append(func(*args, **kwargs))
    683                 if len(self) == 1:
    684                     return result[0]

~/miniconda3/envs/basicf/lib/python3.8/site-packages/proplot/axes/plot.py in wrapper(self, *args, **kwargs)
   3976         @functools.wraps(func)
   3977         def wrapper(self, *args, **kwargs):
-> 3978             return driver(self, func, *args, **kwargs)
   3979         name = func.__name__
   3980         if name not in proplot_methods:

~/miniconda3/envs/basicf/lib/python3.8/site-packages/proplot/axes/plot.py in boxplot_wrapper(self, func, color, fill, fillcolor, fillalpha, lw, linewidth, orientation, marker, markersize, boxcolor, boxlw, capcolor, caplw, meancolor, meanlw, mediancolor, medianlw, whiskercolor, whiskerlw, fliercolor, flierlw, *args, **kwargs)
   1918                 f'got {orientation!r}.'
   1919             )
-> 1920     obj = func(self, *args, **kwargs)
   1921     if not args:
   1922         return obj

~/miniconda3/envs/basicf/lib/python3.8/site-packages/proplot/axes/plot.py in wrapper(self, *args, **kwargs)
   3976         @functools.wraps(func)
   3977         def wrapper(self, *args, **kwargs):
-> 3978             return driver(self, func, *args, **kwargs)
   3979         name = func.__name__
   3980         if name not in proplot_methods:

~/miniconda3/envs/basicf/lib/python3.8/site-packages/proplot/axes/plot.py in standardize_1d(self, func, autoformat, *args, **kwargs)
    529                     kw[xname + 'label'] = label
    530             # Reversed axis
--> 531             if name not in ('scatter',) and len(x) > 1 and xi is None and x[1] < x[0]:
    532                 kw[xname + 'reverse'] = True
    533 

ValueError: operands could not be broadcast together with shapes (20,) (10,) 

### Equivalent steps in matplotlib

```python
import numpy as np
import matplotlib.pyplot as plt

rng = np.random.default_rng()

x = np.array([rng.standard_normal(10), 
              rng.standard_normal(20), 
              rng.standard_normal(30)],
             dtype='object')

fig, ax = plt.subplots()
ax.boxplot(x)
```

### Proplot version

proplot 0.6.4
matplotlib 3.2.2

**Comment by lukelbd** [comment]
Glad to be back! This is now fixed (b9cae662).

Felt I had to take a hiatus for the sake of my graduate degree, but my plan is now 1) release v0.7, then 2) work on proplot at a more measured/even pace going forward.

**Comment by lukelbd** [comment]
Here's your example:

```python
import numpy as np
import proplot as plot

rng = np.random.default_rng()
N = 50
x = np.array([rng.standard_normal(N),
              rng.standard_normal(N * 2),
              rng.standard_normal(N * 3)],
             dtype='object')

fig, ax = plot.subplots()
ax.boxplot(x.T)
fig.show()
```

![tmp](https://user-images.githubusercontent.com/19657652/125208380-37b78580-e24f-11eb-86cc-ec06eb92e4a5.png)

**Comment by kinyatoride** [comment]
Thanks, Luke! I really like v0.7!
