### ISSUE TITLE
Allow nan values in indicate_error

### ISSUE THREAD

**Issue by kinyatoride** [lukelbd/proplot#257]
### Description

It would be nice if `indicate_error` has an option to skip nan values in the input data. Currently, means and stds are not drawn if there is a nan value.
 
### Steps to reproduce
```python
import numpy as np
import proplot as plot

x = np.arange(10)
rng = np.random.default_rng()
y = rng.standard_normal((100, 10))
y[5, 5] = np.nan

fig, ax = plot.subplots()
ax.plot(x, y, means=True)
```

**Actual behavior**: [What actually happened]
![Screen Shot 2021-07-07 at 18 04 08](https://user-images.githubusercontent.com/61028484/124846471-bc538c80-df4d-11eb-8b1f-bf8b9eb267e7.png)

### Proplot version

0.6.4

**Comment by lukelbd** [comment]
This was simple to fix -- just changed `np.mean`, `np.percentile`, and `np.std` calls to `np.nanmean`, `np.nanpercentile`, and `np.nanstd` (83ee1eb). These nan functions also seem to correctly handle masked ndarrays.

**Comment by kinyatoride** [comment]
Hi @lukelbd, it seems like this issue appears again in v0.8.0. It does show the mean value but not standard deviation anymore.

**Comment by lukelbd** [comment]
Thanks -- this got lost in the `plot.py` refactor. Just pushed a 2-line fix, you can install the development version.
