### ISSUE TITLE
Error with legend of indicate_error

### ISSUE THREAD

**Issue by kinyatoride** [lukelbd/proplot#260]
### Description

Proplot 0.7.0 cannot handle combined labels for line and maker passed to `indicate_error`. 
Related to #187. 

### Steps to reproduce

```python
import numpy as np
import pandas as pd
import proplot as plot

rng = np.random.default_rng()

x = rng.standard_normal((100, 10))
x = pd.DataFrame(x)
x.name = 'data'

fig, ax = plot.subplots()
h = ax.plot(x, means=True, shadepctiles=(5,95), label='1')
#h = ax.plot(x, means=True, shadepctiles=(5,95), label='1', legend='ll') # This works

ax.legend(h)
```

**Expected behavior**: [What you expected to happen]
![Screen Shot 2021-07-12 at 17 14 58](https://user-images.githubusercontent.com/61028484/125371018-b3d7c900-e334-11eb-9260-9403019e7bf4.png)

**Actual behavior**: [What actually happened]
python3.8/site-packages/proplot/axes/plot.py:4184: UserWarning: The handle <matplotlib.collections.PolyCollection object at 0x2ad831c53d00> has a label of '_collection0' which cannot be automatically added to the legend.
  return mlegend.Legend(self, *zip(*pairs), ncol=ncol, **kwargs)

![Screen Shot 2021-07-12 at 17 15 32](https://user-images.githubusercontent.com/61028484/125371053-c5b96c00-e334-11eb-8614-90088d8d9676.png)

### Proplot version

0.7.0

**Comment by lukelbd** [comment]
Thanks. Legend entries can be combined in matplotlib by passing tuples to `legend()` -- for example, `ax.legend([(line_obj, shading_obj)], ['line_plus_shading_label'])`. So in this example you just need to pass `[h]` to `legend()` instead of `h`.

However since matplotlib's `plot` always returns lists of handles, it probably makes more sense if `plot` with error indications returns the singleton list `[(line_obj, shading_obj)]` rather than the current behavior `(line_obj, shading_obj)`. Will implement this.

**Comment by kinyatoride** [comment]
Thanks for the response. Just for your info, `ax.legend([h])` does not work in this case. It gives the following error.
`python3.8/site-packages/proplot/axes/plot.py:4105: UserWarning: The handle <matplotlib.collections.PolyCollection object at 0x2afeff71afd0> has a label of '_collection0' which cannot be automatically added to the legend.
  leg = mlegend.Legend(`

I had to pass `ax.legend([tuple(h)], ['label'])`  to make it work. `ax.legend(h)` was working in version 0.6.4 and it was useful when I had multiple lines in multiple axs.

**Comment by lukelbd** [comment]
I see, that's definitely annoying -- `plot` should be returning tuples. Thanks for the report.
