### ISSUE TITLE
Linear ticks for LogLocator

### ISSUE THREAD

**Issue by zxdawn** [lukelbd/proplot#261]
### Description

The official tutorial adds the ticks for LogLocator like this: `xlocator='log', xminorlocator='logminor'`.
But, if I manually set the ticks to linear one, it doesn't work well.

### Steps to reproduce

```python
fig, axs = plot.subplots(share=0)
axs.format(xlim=(1, 18), xlocator='log', xminorlocator=1, xtickminor=True)
```

**Expected behavior**:
The minor ticks should follow what we set in the format.
![image](https://user-images.githubusercontent.com/30388627/125421504-a0d39a66-e35d-4823-8b83-8e88d52637e7.png)

See the matplotlib code below.

**Actual behavior**:
![image](https://user-images.githubusercontent.com/30388627/125419781-7198d398-74f7-4b18-b4c2-e7cfe650043f.png)

### Equivalent steps in matplotlib

```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import FormatStrFormatter

fig, ax = plt.subplots()
ax.plot([1, 10, 15], [1,2,3])
ax.set_xscale('log')
ax.xaxis.set_minor_locator(matplotlib.ticker.LinearLocator(17))
```

### Proplot version

0.6.4

**Comment by lukelbd** [comment]
This is probably related to #219 --  it is fixed as of v0.7.0 (released Sunday). Also btw to match the first image you will need `xscale='log'`. Here's what I get:

```python
fig, axs = pplt.subplots(share=0)
axs.format(xlim=(1, 18), xscale='log', xlocator='log', xminorlocator=1, xtickminor=True)
```

![figure](https://user-images.githubusercontent.com/19657652/125529465-bdd23410-def0-4310-b744-09b52cb0a804.png)
