### ISSUE TITLE
How to rotate the latlabels/lonlabels? 

### ISSUE THREAD

**Issue by zhuyu-ynu** [lukelbd/proplot#269]
### Description

[Description of the bug or feature.]

### Steps to reproduce

A "[Minimal, Complete and Verifiable Example](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)" will make it much easier for maintainers to help you.

```python
# your code here
# we should be able to copy-paste this into python and exactly reproduce your bug
```

**Expected behavior**: [What you expected to happen]

**Actual behavior**: [What actually happened]

### Equivalent steps in matplotlib

Please make sure this bug is related to a specific proplot feature. If you're not sure, try to replicate it with the [native matplotlib API](https://matplotlib.org/3.1.1/api/index.html). Matplotlib bugs belong on the [matplotlib github page](https://github.com/matplotlib/matplotlib).

```python
# your code here, if applicable
```

### Proplot version

Paste the results of `import matplotlib; print(matplotlib.__version__); import proplot; print(proplot.version)`here.

**Comment by lukelbd** [comment]
Assuming you're talking about cartopy's [`rotate_labels` feature](https://scitools.org.uk/cartopy/docs/latest/matplotlib/gridliner.html#cartopy.mpl.gridliner.Gridliner) -- you can pass `rotatelabels=True` to [`GeoAxes.format`](https://proplot.readthedocs.io/en/latest/api/proplot.axes.GeoAxes.format.html) or set `rc['grid.rotatelabels'] = True` to do this globally.
