### ISSUE TITLE
Support adjusting the element size of legend

### ISSUE THREAD

**Issue by zxdawn** [lukelbd/proplot#270]
### Description

Sometimes, the plotted scatter size is small or big, we need to adjust the size in the legend to make it easier to read.

### Steps to reproduce

```python
import proplot as pplt
import numpy as np

def rand_data():
    return np.random.uniform(low=0., high=1., size=(100,))

# Generate data.
x1, y1 = [rand_data() for i in range(2)]
x2, y2 = [rand_data() for i in range(2)]

fig, axs = pplt.subplots()
s1 = axs.scatter(x1, y1, marker='o', label='first', s=2, c='b')
s2 = axs.scatter(x2, y2, marker='o', label='second', s=3, c='r')
axs.legend([s1, s2], loc='r', ncols=1)
```

**Expected behavior**:
Support `size=()` in `axs.legend()`.

**Actual behavior**:
![image](https://user-images.githubusercontent.com/30388627/130401384-572c4ad8-7af8-4181-8a9d-a66018c24f08.png)

I have to adjust the scatter size in the legend manually:
```
legend = axs.legend([s1, s2], loc='r', ncols=1)

legend.legendHandles[0]._sizes = [30]
legend.legendHandles[1]._sizes = [30]
```
![image](https://user-images.githubusercontent.com/30388627/130401522-8f7c6f0c-0609-47af-863d-d8e92a8a8855.png)

### Equivalent steps in matplotlib

```python
import matplotlib.pyplot as plt
import numpy as np

def rand_data():
    return np.random.uniform(low=0., high=1., size=(100,))

# Generate data.
x1, y1 = [rand_data() for i in range(2)]
x2, y2 = [rand_data() for i in range(2)]

plt.figure()
plt.scatter(x1, y1, marker='o', label='first', s=2., c='b')
plt.scatter(x2, y2, marker='o', label='second', s=3., c='r')
# Plot legend.
lgnd = plt.legend(loc="lower right", scatterpoints=1, fontsize=10)
lgnd.legendHandles[0]._sizes = [30]
lgnd.legendHandles[1]._sizes = [30]
```

### Proplot version

0.7.0

**Comment by lukelbd** [comment]
This is already a feature :). You can pass line properties to [Axes.legend](https://proplot.readthedocs.io/en/latest/api/proplot.axes.Axes.legend.html). Here's with `linewidth=3`:


```python
import proplot as pplt
import numpy as np

def rand_data():
    return np.random.uniform(low=0., high=1., size=(100,))

# Generate data.
x1, y1 = [rand_data() for i in range(2)]
x2, y2 = [rand_data() for i in range(2)]

fig, axs = pplt.subplots()
s1 = axs.scatter(x1, y1, marker='o', label='first', s=2, c='b')
s2 = axs.scatter(x2, y2, marker='o', label='second', s=3, c='r')
axs.legend([s1, s2], loc='r', ncols=1, linewidth=3)
```

![example](https://user-images.githubusercontent.com/19657652/130411531-e5223e95-b90a-483b-9863-c3faeb7291b4.png)

**Comment by lukelbd** [comment]
(Might require an update to the latest version)

**Comment by zxdawn** [comment]
Got it! Maybe, it's better to add the example to the legend section? (many matplotlib questions on StackOverflow discussed something like this).

**Comment by zxdawn** [comment]
I test it with a larger size and it looks strange:

```
import proplot as pplt
import numpy as np

def rand_data():
    return np.random.uniform(low=0., high=1., size=(100,))

# Generate data.
x1, y1 = [rand_data() for i in range(2)]
x2, y2 = [rand_data() for i in range(2)]

fig, axs = pplt.subplots()
s1 = axs.scatter(x1, y1, marker='o', label='first', s=2, c='b')
s2 = axs.scatter(x2, y2, marker='o', label='second', s=3, c='r')
axs.legend([s1, s2], loc='r', ncols=1, linewidth=6, markersize=6)
```

![image](https://user-images.githubusercontent.com/30388627/130412820-974652a3-4f60-4102-bbe4-87fe06895e37.png)

The manual settings work well for large values:
```
legend = axs.legend([s1, s2], loc='r', ncols=1)

legend.legendHandles[0]._sizes = [50]
legend.legendHandles[1]._sizes = [50]
```

![image](https://user-images.githubusercontent.com/30388627/130413025-99408525-b888-4624-b8ab-529e785bf357.png)

**Comment by lukelbd** [comment]
Yeah noticed that too... in your example it looks like you're doing the equivalent of `Collection.set_sizes()` on the marker collection. In my example I'm doing the equivalent of `Collection.set_linewidth()` which (evidently) has some weird side-effects for this type of marker. I've added a 2-line workaround since this is probably a really common use-case for the "on-the-fly handle modification" feature. Now passing `markersize=N` will update scatter marker sizes without the weird side effect.

You can install the dev branch for this example to work: `pip install git+https://github.com/lukelbd/proplot.git`.


```python
import proplot as pplt
import numpy as np

def rand_data():
    return np.random.uniform(low=0., high=1., size=(100,))

# Generate data.
x1, y1 = [rand_data() for i in range(2)]
x2, y2 = [rand_data() for i in range(2)]

fig, axs = pplt.subplots()
s1 = axs.scatter(x1, y1, marker='o', label='first', s=2, c='b')
s2 = axs.scatter(x2, y2, marker='o', label='second', s=3, c='r')
# axs.legend([s1, s2], loc='r', ncols=1)
leg = axs.legend([s1, s2], loc='r', ncols=1, markersize=40)
```

![test](https://user-images.githubusercontent.com/19657652/130419794-178359eb-5287-4383-87c1-5992f01be049.png)

**Comment by zxdawn** [comment]
@lukelbd Thanks for the modification!
