### ISSUE TITLE
Line on a map projection not plotted correctly

### ISSUE THREAD

**Issue by JeremyBloxham** [lukelbd/proplot#274]
### Description

When plotting a line on a projection, 360 degrees gets added to the longitude of each point, except the first, resulting in the line wrapping around the globe between the first and second points.

### Steps to reproduce

import proplot as pplt
lons = [307., 292., 280., 269., 259., 249., 239., 228.]
lats = [ 51.,  32.,  11.,  -8., -24., -36., -46., -54.]
fig, ax = pplt.subplots(proj='cyl',basemap=False, width=20, height=12, proj_kw={'lon_0': 180})
ax.plot(lons, lats)

**Expected behavior**: line without 360 degree warp

**Actual behavior**: first point wrapped 360 degrees.

### Equivalent steps in matplotlib

Please make sure this bug is related to a specific proplot feature. If you're not sure, try to replicate it with the [native matplotlib API](https://matplotlib.org/3.1.1/api/index.html). Matplotlib bugs belong on the [matplotlib github page](https://github.com/matplotlib/matplotlib).

```python
# your code here, if applicable
```

### Proplot version

3.3.3.   0.8.1

**Comment by lukelbd** [comment]
This was due to unnecessary normalization of 1D geographic data attempting to make it "monotonic" for user convenience. But the algorithm was full of holes -- among other things it failed for descending data like in your example. Have simply revmoed that bit of code (c8a8faa).
