### ISSUE TITLE
`facecolors` isn't passed into `ax.scatter()`

### ISSUE THREAD

**Issue by zxdawn** [lukelbd/proplot#275]
### Description

If I set `facecolors='none'`, the scatters are still filled with default color.

### Steps to reproduce

```python
import numpy as np
import proplot as pplt

x = np.random.randn(60) 
y = np.random.randn(60)

fig, axs = pplt.subplots()
axs.scatter(x, y, s=80, facecolors='none', edgecolors='r')
```

**Expected behavior**:
Like the old version (0.7.0) of proplot, the scatters are not filled.
![image](https://user-images.githubusercontent.com/30388627/132112986-3f70bdda-7c4e-4bdb-9ab6-e666d395ec83.png)

**Actual behavior**:
![image](https://user-images.githubusercontent.com/30388627/132112686-b0fc9b36-51b2-4548-9b27-26eda8aeeecc.png)

### Equivalent steps in matplotlib

```python
import matplotlib.pyplot as plt 
import numpy as np 

x = np.random.randn(60) 
y = np.random.randn(60)

plt.scatter(x, y, s=80, facecolors='none', edgecolors='r')
plt.show()
```

### Proplot version

Paste the results of `import matplotlib; print(matplotlib.__version__); import proplot; print(proplot.version)`here.
```
3.3.4
0.8.1
```

**Comment by lukelbd** [comment]
Thanks for the report. For now you can use `c`, `color`, or `colors` instead of `facecolors` (you will get the same result). This has to do with how proplot overrides matplotlib's native scatter-plot property cycling.

**Comment by zxdawn** [comment]
Thanks, the `c` works well:
```
import numpy as np
import proplot as pplt

x = np.random.randn(60) 
y = np.random.randn(60)

fig, axs = pplt.subplots()
axs.scatter(x, y, s=80, c='none', edgecolors='r')
```

![image](https://user-images.githubusercontent.com/30388627/132148622-b18bef65-5ff9-432e-a418-e04f105cae42.png)

**Comment by lukelbd** [comment]
Fixed this by simply interpreting `facecolors` the same as `c` and `colors` (690adec). Internally matplotlib uses `colors` for the `PathCollection` "face colors" anyway so this approach is justified.
