### ISSUE TITLE
Issue with one level contour plot with a specified color

### ISSUE THREAD

**Issue by kinyatoride** [lukelbd/proplot#281]
### Description

This error happens only when line color is provided for a contour plot with one level. Proplot does not show the contour in this case.

### Steps to reproduce
```python
import xarray as xr
import numpy as np
import proplot as pplt

da = xr.DataArray(
     np.array(
      [[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]]),
     dims=['y', 'x'])

fig, ax = pplt.subplots()

m = ax.contour(da, levels = [5], colors='k')
```

**Expected behavior**: [Matplotlib outputs]
![Screen Shot 2021-09-14 at 11 32 34](https://user-images.githubusercontent.com/61028484/133314029-3363f8b3-0070-4c4d-ae4f-9342e29e8a51.png)

**Actual behavior**: [What actually happened]
![Screen Shot 2021-09-14 at 11 33 08](https://user-images.githubusercontent.com/61028484/133314106-4acc045d-7ff1-4071-a4a2-454dd2a615f8.png)

### Equivalent steps in matplotlib
```python
import xarray as xr
import numpy as np
import matplotlib.pyplot as plt

da = xr.DataArray(
     np.array(
      [[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]]),
     dims=['y', 'x'])

fig, ax = plt.subplots()

m = ax.contour(da.x, da.y, da, levels = [5], colors='k')
```

### Proplot version
matplotlib 3.4.3
proplot 0.8.1

**Comment by lukelbd** [comment]
Thanks, this was a pretty straightforward fix.
