### ISSUE TITLE
create subplots error

### ISSUE THREAD

**Issue by heylsitan** [lukelbd/proplot#282]
### Description

[Description of the bug or feature.]

### Steps to reproduce

A "[Minimal, Complete and Verifiable Example](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)" will make it much easier for maintainers to help you.

```python
# your code here
# we should be able to copy-paste this into python and exactly reproduce your bug
```
pplt.subplots(ncols=4, proj={2: 'cyl', (3, 4): 'stere'})

**Expected behavior**: [What you expected to happen]
create subplots
**Actual behavior**: [What actually happened]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data1/tools/anaconda3/envs/atmpy/lib/python3.8/site-packages/proplot/ui.py", line 181, in subplots
    axs = fig.add_subplots(*args, **kw_subplots, **kw_gridspec)
  File "/data1/tools/anaconda3/envs/atmpy/lib/python3.8/site-packages/proplot/figure.py", line 1309, in add_subplots
    proj = _axes_dict(naxs, proj, kw=False, default='cartesian')
  File "/data1/tools/anaconda3/envs/atmpy/lib/python3.8/site-packages/proplot/figure.py", line 1262, in _axes_dict
    for nums, item in value.items():
UnboundLocalError: local variable 'value' referenced before assignment

### Equivalent steps in matplotlib

Please make sure this bug is related to a specific proplot feature. If you're not sure, try to replicate it with the [native matplotlib API](https://matplotlib.org/3.1.1/api/index.html). Matplotlib bugs belong on the [matplotlib github page](https://github.com/matplotlib/matplotlib).

```python
# your code here, if applicable
```
![image](https://user-images.githubusercontent.com/6396737/133375208-38abaddc-1bfb-46a3-a4de-5dafe1ba45ac.png)

### Proplot version
0.9.0
Paste the results of `import matplotlib; print(matplotlib.__version__); import proplot; print(proplot.version)`here.

**Comment by lukelbd** [comment]
Hi, this was fixed in v0.9.1 -- just upgrade proplot. See #279

**Comment by heylsitan** [comment]
I use the command  "conda upgrade proplot", the version is just 0.9.0, how to upgrade to 0.9.1?

**Comment by lukelbd** [comment]
That should have worked... it's in the feedstock. Try `conda install proplot==0.9.1`

**Comment by lukelbd** [comment]
`conda upgrade proplot` works on my machine, not sure what your problem was.

**Comment by heylsitan** [comment]
![image](https://user-images.githubusercontent.com/6396737/133378046-d948d987-1880-4ce2-b6f3-9f87f387bef6.png)

**Comment by heylsitan** [comment]
I see. I use the source from tsinghua.edu.cn.

**Comment by lukelbd** [comment]
Hmm well it was just released. Maybe the servers haven’t built a linux version yet. I’d suggest giving it a day or install with pip instead (e.g. pip install proplot==0.9.1).

**Comment by heylsitan** [comment]
OK!
