### ISSUE TITLE
3d axes failing with `UFuncTypeError`

### ISSUE THREAD

**Issue by scottstanie** [lukelbd/proplot#289]
### Description

3D axes seem to fail with a matplotlib error after popping up. 

### Steps to reproduce

```python
import Python 3.8.6 | packaged by conda-forge | (default, Oct  7 2020, 18:42:56)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.18.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import proplot as pplt
In [2]: fig = pplt.figure()
In [3]: fig.subplots(proj='3d')
Out[3]: SubplotGrid(nrows=1, ncols=1, length=1)

In [4]: pplt.show()
```

**Expected behavior**: [What you expected to happen]

**Actual behavior**: [What actually happened]
```

Traceback (most recent call last):
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/backends/backend_qt5.py", line 480, in _draw_idle
    self.draw()
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/proplot/figure.py", line 452, in _canvas_preprocess
    return func(self, *args, **kwargs)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 407, in draw
    self.figure.draw(self.renderer)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/figure.py", line 1863, in draw
    mimage._draw_list_compositing_images(
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/proplot/axes/base.py", line 1500, in draw
    super().draw(renderer, *args, **kwargs)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 464, in draw
    super().draw(renderer)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 411, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 2748, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/mpl_toolkits/mplot3d/art3d.py", line 107, in draw
    [self._position3d, self._position3d + self._dir_vec], renderer.M)
numpy.core._exceptions._UFuncNoLoopError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U21'), dtype('<U21')) -> dtype('<U21')
```
### Equivalent steps in matplotlib

Please make sure this bug is related to a specific proplot feature. If you're not sure, try to replicate it with the [native matplotlib API](https://matplotlib.org/3.1.1/api/index.html). Matplotlib bugs belong on the [matplotlib github page](https://github.com/matplotlib/matplotlib).

```python

In [8]: import matplotlib.pyplot as plt
In [9]: fig = plt.figure()
In [10]: fig.add_subplot(projection='3d')
Out[10]: <Axes3DSubplot:>
In [11]: plt.show()
# no error occurs, empty axes are shown
```

When I ran it in a Jupyter notebook, there's a longer traceback, but the final error is the same
<details>
Error in callback <function install_repl_displayhook.<locals>.post_execute at 0x1200dc550> (for post_execute):

---------------------------------------------------------------------------
UFuncTypeError                            Traceback (most recent call last)
~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/pyplot.py in post_execute()
    136             def post_execute():
    137                 if matplotlib.is_interactive():
--> 138                     draw_all()
    139 
    140             # IPython >= 2

~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/_pylab_helpers.py in draw_all(cls, force)
    135         for manager in cls.get_all_fig_managers():
    136             if force or manager.canvas.figure.stale:
--> 137                 manager.canvas.draw_idle()
    138 
    139 

~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/backend_bases.py in draw_idle(self, *args, **kwargs)
   2010         if not self._is_idle_drawing:
   2011             with self._idle_draw_cntx():
-> 2012                 self.draw(*args, **kwargs)
   2013 
   2014     @cbook.deprecated("3.2")

~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/proplot/figure.py in _canvas_preprocess(self, *args, **kwargs)
    450         with ctx1, ctx2, ctx3:
    451             fig.auto_layout()
--> 452             return func(self, *args, **kwargs)
    453 
    454     # Add preprocessor

~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py in draw(self)
    405              (self.toolbar._wait_cursor_for_draw_cm() if self.toolbar
    406               else nullcontext()):
--> 407             self.figure.draw(self.renderer)
    408             # A GUI class may be need to update a window using this draw, so
    409             # don't forget to call the superclass.

~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     39                 renderer.start_filter()
     40 
---> 41             return draw(artist, renderer, *args, **kwargs)
     42         finally:
     43             if artist.get_agg_filter() is not None:

~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/figure.py in draw(self, renderer)
   1861 
   1862             self.patch.draw(renderer)
-> 1863             mimage._draw_list_compositing_images(
   1864                 renderer, self, artists, self.suppressComposite)
   1865 

~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    130     if not_composite or not has_images:
    131         for a in artists:
--> 132             a.draw(renderer)
    133     else:
    134         # Composite any adjacent images together

~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/proplot/axes/base.py in draw(self, renderer, *args, **kwargs)
   1498         if self._inset_parent is not None and self._inset_zoom:
   1499             self.indicate_inset_zoom()
-> 1500         super().draw(renderer, *args, **kwargs)
   1501 
   1502     def get_tightbbox(self, renderer, *args, **kwargs):

~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     39                 renderer.start_filter()
     40 
---> 41             return draw(artist, renderer, *args, **kwargs)
     42         finally:
     43             if artist.get_agg_filter() is not None:

~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/mpl_toolkits/mplot3d/axes3d.py in draw(self, renderer)
    462 
    463         # Then rest
--> 464         super().draw(renderer)
    465 
    466     def get_axis_position(self):

~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     39                 renderer.start_filter()
     40 
---> 41             return draw(artist, renderer, *args, **kwargs)
     42         finally:
     43             if artist.get_agg_filter() is not None:

~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py in wrapper(*inner_args, **inner_kwargs)
    409                          else deprecation_addendum,
    410                 **kwargs)
--> 411         return func(*inner_args, **inner_kwargs)
    412 
    413     return wrapper

~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/axes/_base.py in draw(self, renderer, inframe)
   2746             renderer.stop_rasterizing()
   2747 
-> 2748         mimage._draw_list_compositing_images(renderer, self, artists)
   2749 
   2750         renderer.close_group('axes')

~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    130     if not_composite or not has_images:
    131         for a in artists:
--> 132             a.draw(renderer)
    133     else:
    134         # Composite any adjacent images together

~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     39                 renderer.start_filter()
     40 
---> 41             return draw(artist, renderer, *args, **kwargs)
     42         finally:
     43             if artist.get_agg_filter() is not None:

~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/mpl_toolkits/mplot3d/art3d.py in draw(self, renderer)
    105     def draw(self, renderer):
    106         proj = proj3d.proj_trans_points(
--> 107             [self._position3d, self._position3d + self._dir_vec], renderer.M)
    108         dx = proj[0][1] - proj[0][0]
    109         dy = proj[1][1] - proj[1][0]

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U21'), dtype('<U21')) -> dtype('<U21')

---------------------------------------------------------------------------
UFuncTypeError                            Traceback (most recent call last)
~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/IPython/core/formatters.py in __call__(self, obj)
    339                 pass
    340             else:
--> 341                 return printer(obj)
    342             # Finally look for special method names
    343             method = get_real_method(obj, self.print_method)

~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/IPython/core/pylabtools.py in <lambda>(fig)
    248         png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))
    249     if 'retina' in formats or 'png2x' in formats:
--> 250         png_formatter.for_type(Figure, lambda fig: retina_figure(fig, **kwargs))
    251     if 'jpg' in formats or 'jpeg' in formats:
    252         jpg_formatter.for_type(Figure, lambda fig: print_figure(fig, 'jpg', **kwargs))

~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/IPython/core/pylabtools.py in retina_figure(fig, **kwargs)
    138 def retina_figure(fig, **kwargs):
    139     """format a figure as a pixel-doubled (retina) PNG"""
--> 140     pngdata = print_figure(fig, fmt='retina', **kwargs)
    141     # Make sure that retina_figure acts just like print_figure and returns
    142     # None when the figure is empty.

~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/IPython/core/pylabtools.py in print_figure(fig, fmt, bbox_inches, **kwargs)
    130         FigureCanvasBase(fig)
    131 
--> 132     fig.canvas.print_figure(bytes_io, **kw)
    133     data = bytes_io.getvalue()
    134     if fmt == 'svg':

~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/proplot/figure.py in _canvas_preprocess(self, *args, **kwargs)
    450         with ctx1, ctx2, ctx3:
    451             fig.auto_layout()
--> 452             return func(self, *args, **kwargs)
    453 
    454     # Add preprocessor

~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, pad_inches, bbox_extra_artists, backend, **kwargs)
   2191                            else suppress())
   2192                     with ctx:
-> 2193                         self.figure.draw(renderer)
   2194 
   2195                     bbox_inches = self.figure.get_tightbbox(

~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     39                 renderer.start_filter()
     40 
---> 41             return draw(artist, renderer, *args, **kwargs)
     42         finally:
     43             if artist.get_agg_filter() is not None:

~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/figure.py in draw(self, renderer)
   1861 
   1862             self.patch.draw(renderer)
-> 1863             mimage._draw_list_compositing_images(
   1864                 renderer, self, artists, self.suppressComposite)
   1865 

~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    130     if not_composite or not has_images:
    131         for a in artists:
--> 132             a.draw(renderer)
    133     else:
    134         # Composite any adjacent images together

~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/proplot/axes/base.py in draw(self, renderer, *args, **kwargs)
   1498         if self._inset_parent is not None and self._inset_zoom:
   1499             self.indicate_inset_zoom()
-> 1500         super().draw(renderer, *args, **kwargs)
   1501 
   1502     def get_tightbbox(self, renderer, *args, **kwargs):

~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     39                 renderer.start_filter()
     40 
---> 41             return draw(artist, renderer, *args, **kwargs)
     42         finally:
     43             if artist.get_agg_filter() is not None:

~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/mpl_toolkits/mplot3d/axes3d.py in draw(self, renderer)
    462 
    463         # Then rest
--> 464         super().draw(renderer)
    465 
    466     def get_axis_position(self):

~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     39                 renderer.start_filter()
     40 
---> 41             return draw(artist, renderer, *args, **kwargs)
     42         finally:
     43             if artist.get_agg_filter() is not None:

~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py in wrapper(*inner_args, **inner_kwargs)
    409                          else deprecation_addendum,
    410                 **kwargs)
--> 411         return func(*inner_args, **inner_kwargs)
    412 
    413     return wrapper

~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/axes/_base.py in draw(self, renderer, inframe)
   2746             renderer.stop_rasterizing()
   2747 
-> 2748         mimage._draw_list_compositing_images(renderer, self, artists)
   2749 
   2750         renderer.close_group('axes')

~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    130     if not_composite or not has_images:
    131         for a in artists:
--> 132             a.draw(renderer)
    133     else:
    134         # Composite any adjacent images together

~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     39                 renderer.start_filter()
     40 
---> 41             return draw(artist, renderer, *args, **kwargs)
     42         finally:
     43             if artist.get_agg_filter() is not None:

~/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/mpl_toolkits/mplot3d/art3d.py in draw(self, renderer)
    105     def draw(self, renderer):
    106         proj = proj3d.proj_trans_points(
--> 107             [self._position3d, self._position3d + self._dir_vec], renderer.M)
    108         dx = proj[0][1] - proj[0][0]
    109         dy = proj[1][1] - proj[1][0]

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U21'), dtype('<U21')) -> dtype('<U21')

Figure(nrows=1, ncols=1, refwidth=2.5)
</details>

### Proplot version

```
In [12]: import matplotlib; print(matplotlib.__version__); import proplot; print(proplot.version)
3.3.0
0.9.1
```

**Comment by lukelbd** [comment]
Thanks, this is now fixed on master (you can install with `pip install git+https://github.com/lukelbd/proplot.git`).
