### ISSUE TITLE
Norm keywords aren't passing properly to colormap

### ISSUE THREAD

**Issue by bradyrx** [lukelbd/proplot#29]
I'm finding that the keywords for e.g. LogNorm are not passing through the wrapper to `matplotlib` appropriately. Using the same data as when we discussed the LogNorm colorbar in https://github.com/lukelbd/proplot/issues/25: http://s000.tinyupload.com/index.php?file_id=02946064711977690771.

Below, see that `proplot` can't modify the `LogNorm` boundaries.

**With proplot**:
```python
f, ax = plot.subplots(proj='pcarree', tight=False, axwidth=6,)

p = ax.contourf(chl.lon, chl.lat, chl.values, norm='log', norm_kw={'vmin': 0.01, 'vmax': 10}, levels=30,
                cmap='Fire', )

ax.format(latlim=(20, 50), lonlim=(-140, -105), land=True)
ax.colorbar(p, loc='r')
```

<img width="556" alt="Screen Shot 2019-09-02 at 10 36 55 AM" src="https://user-images.githubusercontent.com/8881170/64127121-500e0d80-cd65-11e9-89be-a2692d93b998.png">

**With matplotlib**:
```python
f, ax = plt.subplots()
p = plt.pcolormesh(chl.lon, chl.lat, chl.values, norm=colors.LogNorm(vmin=0.01, vmax=1), cmap='Fire')
plt.colorbar(p)
```

<img width="386" alt="Screen Shot 2019-09-02 at 10 38 24 AM" src="https://user-images.githubusercontent.com/8881170/64127165-6ddb7280-cd65-11e9-8449-64fd640b236f.png">

**Comment by lukelbd** [comment]
If you pass `vmin` and `vmax` to `contourf` directly, they will be used:

```python
ax.contourf(chl.lon, chl.lat, chl.values, norm='log', vmin=0.01, vmax=10, levels=30, cmap='Fire', ) 
```

But it's definitely not right to just ignore `norm_kw`. Just pushed a patch (5b09d892), now `cmap_wrapper` checks to see if `vmin` and `vmax` were passed in the `norm_kw` dictionary.

**Comment by bradyrx** [comment]
FYI, this solution doesn't work. I forgot I tried that before.

```python
plot.rc['geogrid.alpha'] = 0

plot.rc.fontname = 'Helvetica Light'
f, ax = plot.subplots(proj='cyl', axwidth='8cm',)
p = ax.contourf(chl.lon, chl.lat, chl, norm='log', vmin=0.01, vmax=10, levels=30)
ax.colorbar(p, loc='r')
ax.format(land=True, latlim=(20, 50), lonlim=((-140, -105)))
```

<img width="298" alt="Screen Shot 2019-09-02 at 4 06 12 PM" src="https://user-images.githubusercontent.com/8881170/64134499-9da56d00-cd9b-11e9-8418-520ff8d469a9.png">

I think you might get this behavior if you use the LogLocator directly. (https://matplotlib.org/3.1.1/gallery/images_contours_and_fields/contourf_log.html)

**Comment by lukelbd** [comment]
Okay this patch seems to do the trick: a3ebbb12. Try:

```python
f, ax = plot.subplots()
ax.pcolormesh(10**(np.random.rand(10,10)*5), vmin=0.1, vmax=10, norm='log', colorbar='r')
```

Previously if you specified both `vmin` and `vmax` I just set the levels to `np.linspace(vmin, vmax, N)`, because most locators treat `vmin` and `vmax` as *suggested* locations, not absolute locations. For example, if you did `vmin=0.1` and `vmax=20`, the actual level maximum would be `10`. But now this is documented, and I think it makes more sense that if you really want exact locations, you must provide your own `levels` array.
