### ISSUE TITLE
Format function to consider custom abc and multiple titles

### ISSUE THREAD

**Issue by pratiman-91** [lukelbd/proplot#294]
### Description

Currently, `abc` does not consider the custom text. A provision can be made to incorporate that. Multiple titles can be incorporated in the `format. I know there are ways that the functions may not be even needed. However, it is for the sake of consistency and making the user end code simple.  

### Steps to reproduce `abc`

**Current Code**:

```python
import proplot as pplt
fig = pplt.figure(space=0, refwidth='10em')
axs = fig.subplots(nrows=3, ncols=2)
axs.format(
    abc='A.', abcloc='ul',
    xticks='null', yticks='null', facecolor='gray5',
    xlabel='x axis', ylabel='y axis',
)
```

**Current behavior**: 
![image](https://user-images.githubusercontent.com/31694629/136650413-84042a9e-75c5-4ab4-bc98-e036225fa2b5.png)

**Modified Code**:

```python
import proplot as pplt
fig = pplt.figure(space=0, refwidth='10em')
axs = fig.subplots(nrows=3, ncols=2)
axs.format(
    abc=('A','B','1','2','a','b'), abcloc='ul',
    xticks='null', yticks='null', facecolor='gray5',
    xlabel='x axis', ylabel='y axis',
)
```
It is expected to use the custom `abc`.

### Steps to reproduce `title`

**Current Code**:

```python
import proplot as pplt
fig = pplt.figure(space=0, refwidth='10em')
axs = fig.subplots(nrows=3, ncols=2)
axs.format(
    ultitle=('Title 1'), 
    xticks='null', yticks='null', facecolor='gray5',
    xlabel='x axis', ylabel='y axis',
)
```

**Current behavior**: 
![image](https://user-images.githubusercontent.com/31694629/136650616-ed7a0882-2fbb-4cd0-ba80-6125fac38734.png)

**Modified Code**:

```python
import proplot as pplt
fig = pplt.figure(space=0, refwidth='10em')
axs = fig.subplots(nrows=3, ncols=2)
axs.format(
    ultitle=('Title 1', 'Title 2', 'Test 1', 'Test2', 'Exp1', 'Exp2'),
    xticks='null', yticks='null', facecolor='gray5',
    xlabel='x axis', ylabel='y axis',
)
```
It is expected to use the `ultitle` for different subplots. Similarly with other titles.

![image](https://user-images.githubusercontent.com/31694629/136650698-ebb4e82e-3b45-4d93-ac66-d1d2e5d04b1b.png)

**Comment by lukelbd** [comment]
This was implemented by #317.
