### ISSUE TITLE
Unexpected behavior when explicitly providing colors and unevenly spaced levels

### ISSUE THREAD

**Issue by AWSisco** [lukelbd/proplot#299]
### Description

When supplying my own colors and unevenly spaced levels explicitly, I observe an unexpected behavior where some colors are omitted and others are repeated.

### Steps to reproduce

```python
import proplot as pplt
import numpy as np

N=20
state=np.random.RandomState(51423)
data=np.cumsum(state.rand(N, N), axis=1)

colors=['white','indigo1','indigo3','indigo5','indigo7','indigo9','yellow1','yellow3','yellow5','yellow7','yellow9','violet1','violet3']

fig,axs=pplt.subplots(nrows=2, ncols=1, refheight=3.5)

axs[0].pcolormesh(data, levels=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                  colors=colors, colorbar='r', extend='both', colorbar_kw={'label':'Expected color distribution'})

axs[1].pcolormesh(data,levels=[1., 1.25, 1.5, 2., 2.5, 3., 3.75, 4.5, 6., 7.5, 9., 12.],
                  colors=colors, colorbar='r', extend='both', colorbar_kw={'label':'Unexpected color distribution'})
```

![unexpected_behavior](https://user-images.githubusercontent.com/37667176/139503062-5fc353b0-c840-41ea-8ecd-b407f1deb945.png)

**Expected behavior**: I expected that all 13 named colors would still show when mapped to the unevenly spaced levels on ```axs[1]```.

**Actual behavior**: In this example on ```axs[1]```, some colors are omitted and replaced by others. I also observe this issue when providing my own RGB tuples.

### Equivalent steps in matplotlib

Explicitly providing named colors and unevenly spaced levels in Matplotlib gives the desired behavior.

### Proplot version

ProPlot 0.9.5
Matplotlib 3.4.3
Python 3.9.7

**Comment by lukelbd** [comment]
Huh -- I think this has something to do with [`SegmentedNorm`](https://proplot.readthedocs.io/en/latest/api/proplot.colors.SegmentedNorm.html#proplot.colors.SegmentedNorm), which is applied by default whenever you pass an unevenly-spaced `levels` list. Does passing `norm='linear'` to `pcolormesh` fix the problem? Or alternatively... perhaps `SegmentedNorm` is not getting applied when it should be, so you could try `norm='segmented'`.

**Comment by lukelbd** [comment]
[Here's a demo](https://proplot.readthedocs.io/en/latest/2dplots.html#Special-normalizers) of the effect of `Normalize` (the default linear one) vs. `SegmentedNorm`. This kind of seems like `SegmentedNorm` is somehow not getting applied when it should be... resulting in uneven steps across your color list. You could also try manually passing `norm=pplt.SegmentedNorm(levels)` if `norm='segmented'` does not work.

**Comment by AWSisco** [comment]
Explicitly specifying the ```norm``` doesn't seem to resolve the issue.

```python
import proplot as pplt
import numpy as np

N=20
state=np.random.RandomState(51423)
data=np.cumsum(state.rand(N, N), axis=1)

colors=['white','indigo1','indigo3','indigo5','indigo7','indigo9','yellow1','yellow3','yellow5','yellow7','yellow9','violet1','violet3']
levels_even = pplt.arange(1,12,1)
levels_uneven=[1., 1.25, 1.5, 2., 2.5, 3., 3.75, 4.5, 6., 7.5, 9., 12.]

fig,axs=pplt.subplots(nrows=2, ncols=2, refwidth=3.)

axs[0].pcolormesh(data, levels=levels_even,   colors=colors, colorbar='r', extend='both')
axs[1].pcolormesh(data, levels=levels_uneven, colors=colors, colorbar='r', extend='both', norm='linear')
axs[2].pcolormesh(data, levels=levels_uneven, colors=colors, colorbar='r', extend='both', norm='segmented')
axs[3].pcolormesh(data,                       colors=colors, colorbar='r', extend='both', norm=pplt.SegmentedNorm(levels_uneven))

t = ['Even levels','norm=\'linear\'','norm=\'segmented\'','pplt.SegmentedNorm(levels_uneven)']
for i, ax in enumerate(axs):
    ax.format(title=t[i], titleloc='l')
```

![2x2](https://user-images.githubusercontent.com/37667176/139687243-d9989c9b-3508-4624-97d5-c8ed8bdfa0d3.png)

**Comment by AWSisco** [comment]
After some additional experimenting, I managed to create the desired behavior by manually constructing my ```cmap``` and ```norm``` using ```matplotlib.colors.ListedColormap``` and ```Matplotlib.colors.BoundaryNorm```, respectively. I borrowed some of this from https://github.com/lukelbd/proplot/issues/190, so perhaps my issue is related?

The values plotted on ```axs[1]``` are the actual values of the underlying data. I'm not fluent in what's happening under the hood in ProPlot, but maybe this will give some hints to those who are.

```python
import proplot as pplt
import numpy as np
import matplotlib.colors as mcolors

#Some data to plot
N=20
state=np.random.RandomState(51423)
data=np.cumsum(state.rand(N, N), axis=1)

#Colors and levels I want
colors=['white','indigo1','indigo3','indigo5','indigo7','indigo9','yellow1','yellow3','yellow5','yellow7','yellow9','violet1','violet3']
levels_uneven=[1., 1.25, 1.5, 2., 2.5, 3., 3.75, 4.5, 6., 7.5, 9., 12.]

#Manually create a colormap from the named colors
colors_list = []
for c in colors:
    colors_list.append(pplt.to_rgb(c))
manual_cmap = mcolors.ListedColormap(colors_list)

norm = mcolors.BoundaryNorm(boundaries=np.array(levels_uneven), ncolors=len(levels_uneven)-1)

fig,axs=pplt.subplots(nrows=1, ncols=2, refwidth=5)

axs[0].pcolormesh(data, levels=levels_uneven, colors=colors, colorbar='r', extend='both', labels=True, precision=2, labels_kw={'size':6})
axs[1].pcolormesh(data, cmap=manual_cmap, norm=norm, colorbar='r', extend='both', labels=True, precision=2, labels_kw={'size':6})

axs[0].format(title='Unexpected behavior', titleloc='l')
axs[1].format(title='Desired behavior with a cmap and norm work-around ', titleloc='l')
```

![desired](https://user-images.githubusercontent.com/37667176/139726555-009b5177-5d89-459d-9109-0248eb446133.png)

**Comment by lukelbd** [comment]
Thanks for the helpful examples! This turned out to be a very quick fix -- it's on the master branch now (you can install with `pip install git+https://github.com/lukelbd/proplot.git`).

**Comment by lukelbd** [comment]
Here's your example after the update. Note some ticks on the right "linear" colorbar are missing by default (to prevent overcrowding) while ticks on the left `SegmentedNorm` colorbar are all shown (to avoid hiding the locations of non-linear thresholds in the color scaling).

```python
import proplot as pplt
import numpy as np
N=20
state=np.random.RandomState(51423)
data=np.cumsum(state.rand(N, N), axis=1)
colors=['white','indigo1','indigo3','indigo5','indigo7','indigo9','yellow1','yellow3','yellow5','yellow7','yellow9','violet1','violet3']
levels_even = pplt.arange(1,12,1)
levels_uneven=[1., 1.25, 1.5, 2., 2.5, 3., 3.75, 4.5, 6., 7.5, 9., 12.]
fig, axs = pplt.subplots(ncols=2, refwidth=3.)
axs[0].pcolor(np.random.rand(10, 10) * 12, levels=levels_uneven, colors=colors, colorbar='r', extend='both')
axs[1].pcolor(np.random.rand(10, 10) * 12, levels=levels_even, colors=colors, colorbar='r', extend='both')
```

![testing](https://user-images.githubusercontent.com/19657652/140000392-1d849158-c10e-4960-97f6-9461879d1319.png)

**Comment by AWSisco** [comment]
Thanks for such a quick turnaround on getting this resolved. Much appreciated!
