### ISSUE TITLE
AttributeError for share=True in subplots()

### ISSUE THREAD

**Issue by lkugler** [lukelbd/proplot#305]
### Description

Hi! I noticed that in the latest version 0.9.5 creating a subplot fails with any share option (after updating from proplot 0.7.0, where it worked). Thanks!

### Steps to reproduce

```python
import proplot as pplt
fig = pplt.figure(share=True)
axs = fig.subplots(nrows=3)
```

**Expected behavior**: No error should be raised.

**Actual behavior**: `AttributeError: 'CartesianAxesSubplot' object has no attribute '_shared_y_axes'`

### Equivalent steps in matplotlib

```python
# your code here, if applicable
import matplotlib.pyplot as plt
plt.subplots(3,3, sharex=True, sharey=True)
```
works without errors

### Proplot version

matplotlib.__version__ = '3.5.0'
pplt.__version__ =  '0.9.5'

**Comment by lukelbd** [comment]
Thanks for the report -- looks like this is another matplotlib 3.5+ issue (if you downgrade to matplotlib 3.4.3 it should work). I'll submit a bugfix release repairing the matplotlib 3.5+ compatibility issues in the coming days.
