### ISSUE TITLE
Slower speed of saving plotted Geographic data with cartopy

### ISSUE THREAD

**Issue by zxdawn** [lukelbd/proplot#306]
### Description

I'm plotting large datasets using proplot (0.9.5.post78) and cartopy (0.20.0). The speed is much slower than the pyplot one.

### Steps to reproduce

```python
import time
import numpy as np
import proplot as pplt
import cartopy.crs as ccrs
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

offset = -40
lon = np.linspace(offset, 360 + offset - 1, 3000)
lat = np.linspace(-60, 60 + 1, 500)
state = np.random.RandomState(51423)
data = state.rand(len(lat), len(lon))

def proplot_test():
    start = time.time()
    fig, axs = pplt.subplots(proj='stere', figsize=(4,4))
    axs.coastlines()
    axs.pcolormesh(lon, lat, data, cmap='viridis')
    end = time.time()
    print('proplot plot cost: ', end - start)
    fig.savefig('test_proplot.jpg', dpi=300)
    save_end = time.time()
    print('proplot save cost: ', save_end - end)

def pyplot_test():
    start = time.time()
    fig, ax = plt.subplots(figsize=(4,4), subplot_kw=dict(projection=ccrs.Stereographic()))
    ax.coastlines()
    ax.pcolormesh(lon, lat, data, cmap='viridis', transform=ccrs.PlateCarree())
    end = time.time()
    print('pyplot plot cost: ', end - start)
    fig.savefig('test_pyplot.jpg', dpi=300)
    save_end = time.time()
    print('pyplot save cost: ', save_end - end)

proplot_test()
pyplot_test()
```

**Expected behavior**: [What you expected to happen]

The speed is similar with pyplot.

**Actual behavior**: [What actually happened]

```
proplot plot cost:  2.1709158420562744
proplot save cost:  5.2430949211120605

pyplot plot cost:  1.9175093173980713
pyplot save cost:  1.4209530353546143
```

In jupyterlab, the cost of plotting data by proplot is 7s while the pyplot one is 3.7s. I suppose this is the same problem of saving figures, because jupyter notebook needs to show the figure inline.

**Comment by zxdawn** [comment]
It seems similar questions have been discussed in #4. Anyway, I tested it with the new version (0.9.5.post78). The problem should have been solved, right?

**Comment by lukelbd** [comment]
The "plot" time difference seems to effectively disappear when I pass `discrete=False` to `pcolormesh` (which mimics matplotlib's behavior). However the "save" time difference remains, which is definitely troubling... I would have suspected the "auto layout" algorithm to be responsible, but fixing the figure size (as in your example) and fixing the spaces (by passing `tight=False` to `subplots`) does nothing. Will look into this.

**Comment by lukelbd** [comment]
Also don't think I can improve the "plot" time when `discrete=True` -- that is a more complex color normalization algorithm that will always be slower for larger datasets. I guess we didn't discover this specific saving issue in #4.

**Comment by lukelbd** [comment]
Found it! This was actually mentioned in #4 -- the slowdown is due proplot's default behavior of [fixing "white lines" between patches](https://github.com/jklymak/contourfIssues). This can be disabled locally by passing `edgefix=False` to `pcolormesh` (or any other plotting command that makes patches) or globally by setting `pplt.rc.edgefix = False`. After doing this, the time difference is only around 0.2 seconds.

I don't think I'll change the default behaviot, because I find `edgefix` useful and "white lines" extremely annoying, but I've added a disclaimer to the top of the "2d plotting" section that warns about this feature (I should have already done this). I also now automatically disable this feature when `rasterized=True`, since "white lines" disappear in rasterized graphics.

**Comment by lukelbd** [comment]
Here's an [even more glaring example](https://stackoverflow.com/q/27092991/4970632) of the "white lines" issue.

**Comment by zxdawn** [comment]
Thanks! I tested with `pplt.rc.edgefix = False` and `axs.pcolormesh(lon, lat, data, cmap='viridis', discrete=False)`, but still got a similar slow saving process:
```
proplot plot cost:  2.173644542694092
proplot save cost:  3.4876692295074463

pyplot plot cost:  1.9262807369232178
pyplot save cost:  1.4552743434906006
```
How did you get ~ 0.2 seconds difference? Do you mean the time difference of plotting or saving?

**Comment by lukelbd** [comment]
Maybe try running the test a few more times? Sometimes weird delays can happen on individual runs. On average I get ~0.1 second difference in matplotlib 3.2.1 and ~0.2 second difference in matplotlib 3.5.0.

**Comment by zxdawn** [comment]
Em ... It still gives the similar result.

Could you provide the the backend by `import matplotlib; print(matplotlib.get_backend())`? It seems that may affect the speed?
I find that my laptop uses `TkAgg` and my HPC uses `agg`.

For TkAgg:
```
proplot plot cost:  2.2397313117980957
proplot save cost:  3.944159984588623
pyplot plot cost:  2.02947735786438
pyplot save cost:  2.988798141479492

```

For agg:
```
proplot plot cost:  11.766062498092651
proplot save cost:  38.967479944229126
pyplot plot cost:  10.71821665763855
pyplot save cost:  10.342122793197632
```

Such a big difference ...

**Comment by lukelbd** [comment]
Whoops -- in my tests I also disabled "tight layout" by passing `tight=False` to `subplots` (proplot enables "tight layout" by default, but matplotlib does not). When I use `tight=True`, I get the same time differences as you. Note that passing `bbox_inches='tight'` to `savefig` in the pyplot example will result in identically "slow" times compared to proplot.

**Comment by lukelbd** [comment]
Tight layout is always expensive in these cases, since matplotlib has to calculate the position of every single tiny box.

**Comment by zxdawn** [comment]
Ha, got it! It's super faster now on my laptop:
```
proplot plot cost:  1.9651808738708496
proplot save cost:  1.9354157447814941
pyplot plot cost:  1.842256784439087
pyplot save cost:  1.5909419059753418
```

But, the speed is both slow on the HPC connected by ssh:
```
proplot plot cost:  12.106668949127197
proplot save cost:  11.959054470062256
pyplot plot cost:  11.182377338409424
pyplot save cost:  9.79730486869812
```
Maybe this is a matplotlib bug ...

**Comment by lukelbd** [comment]
Great! Not so much a "bug" just a limitation of how "tight layout" is calculated -- in order to get the positions of every object in the subplot (and, thus, ensure the subplots are sufficiently separated to prevent overlapping content), we have to draw every object in the subplot. However, it could probably be massively improved by skipping objects that are "clipped" by the subplot edges (i.e., skipping objects with `obj.get_clip_on()` set to `True`). I'll experiment with this for the next version.

**Comment by lukelbd** [comment]
Ok... I decided to do this and it worked *really* well! Now proplot's tight layout algorithm is significantly faster than matplotlib's algorithm in the presence of high-res content. Here are the new time comparisons:

```python
import cartopy.crs as ccrs
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

offset = -40
lon = np.linspace(offset, 360 + offset - 1, 3000)
lat = np.linspace(-60, 60 + 1, 500)
state = np.random.RandomState(51423)
data = state.rand(len(lat), len(lon))

def proplot_test():
    start = time.time()
    pplt.rc.edgefix = False
    fig, axs = pplt.subplots(proj='stere', figsize=(4,4), tight=True)
    axs.coastlines()
    axs.pcolormesh(lon, lat, data, cmap='viridis', discrete=False)
    fig.savefig('~/Downloads/test_proplot.jpg', dpi=300)
    print('proplot save cost: ', time.time() - start)

def pyplot_test():
    start = time.time()
    fig, ax = plt.subplots(figsize=(4,4), subplot_kw=dict(projection=ccrs.Stereographic()))
    ax.coastlines()
    ax.pcolormesh(lon, lat, data, cmap='viridis', transform=ccrs.PlateCarree(), )
    fig.savefig('/Users/ldavis/Downloads/test_pyplot.jpg', dpi=300, bbox_inches='tight')
    print('pyplot save cost: ', time.time() - start)

for _ in range(3):
    proplot_test()
    pyplot_test()
```

Results in:

```
proplot save cost:  3.6952199935913086
pyplot save cost:  5.431581258773804
proplot save cost:  3.6929588317871094
pyplot save cost:  5.605504035949707
proplot save cost:  3.7971720695495605
pyplot save cost:  5.395456075668335
```

**Comment by zxdawn** [comment]
Wow, nice PR!

Finally, I find some Python environment problems causing the slow speed of proplot.

## Code
```
import time
import numpy as np
import cartopy.crs as ccrs
import matplotlib
matplotlib.use('Agg') 

import matplotlib.pyplot as plt 
import proplot as pplt

import warnings
warnings.filterwarnings('ignore')

offset = -40 
lon = np.linspace(offset, 360 + offset - 1, 3000)
lat = np.linspace(-60, 60 + 1, 500)
state = np.random.RandomState(51423)
data = state.rand(len(lat), len(lon))

def pyplot_test():
    start = time.time()
    fig, ax = plt.subplots(figsize=(4,4), subplot_kw=dict(projection=ccrs.Stereographic()))
    ax.coastlines()
    ax.pcolormesh(lon, lat, data, cmap='viridis')#, transform=ccrs.PlateCarree())
    plt.savefig('test_pyplot.jpg', dpi=300)
    print('pyplot save cost: ', time.time() - start)

def proplot_test():
    start = time.time()
    pplt.rc.edgefix = False
    fig, axs = pplt.subplots(proj='stere', figsize=(4,4), tight=False)
    axs.coastlines()
    axs.pcolormesh(lon, lat, data, cmap='viridis', discrete=False)
    fig.savefig('./test_proplot.jpg', dpi=300)
    print('proplot save cost: ', time.time() - start)

pyplot_test()
proplot_test()
```

## Newest version of all packages (proplot: main branch)
### Set up
```
conda install -c conda-forge matplotlib numpy proplot cartopy
```
### Output
```
pyplot save cost:  1.7365918159484863
proplot save cost:  4.591912746429443
```

## Old version of some package and the newest version (main branch) of proplot
### Set up
```
conda install -c conda-forge matplotlib numpy proplot cartopy basemap
```
Basemap will cause some old version of packages.

### Output
```
pyplot save cost:  1.8308396339416504
proplot save cost:  22.83601140975952
```

## Problem
It seems proplot depends on some specific library that can accelerate the plotting by updating to the newest version. Have no idea of which.

## Details of environment
Here's the detail of the environment created above: `cartopy_basemap.yml` and `cartopy_nobasemap.yml`.
[env_yml.tar.gz](https://github.com/lukelbd/proplot/files/7648268/env_yml.tar.gz)

**Comment by zxdawn** [comment]
That should be caused by the old version of `proj`.

Details:

### Description

I tested two new environment:

ENV1 (cartopy_nobasemap): `conda install -c conda-forge matplotlib numpy proplot cartopy`
ENV2  (cartopy_basemap): `conda install -c conda-forge matplotlib numpy proplot cartopy basemap` 

For ENV2, the speed of adding transform to pcolormesh is 20x slower.
Here's the version info of most important packages:
```
ENV1:
Python 3.10.0
matplotlib                3.5.0                    pypi_0    pypi
matplotlib-base           3.5.0           py310h23f4a51_0    conda-forge
cartopy                   0.20.1                   pypi_0    pypi
proj                      8.2.0                h277dcde_0    conda-forge
pyproj                    3.3.0                    pypi_0    pypi

ENV2:
Python 3.9.7
matplotlib                3.5.0            py39hf3d152e_0    conda-forge
matplotlib-base           3.5.0            py39h2fa2bec_0    conda-forge
cartopy                   0.20.0           py39h2103e0b_0    conda-forge
proj                      8.0.1                h277dcde_0    conda-forge
pyproj                    3.3.0            py39ha9a7ae0_0    conda-forge
basemap                   1.2.2            py39h2103e0b_4    conda-forge
```

The difference is Python, proj and cartopy.
I suppose the difference between `0.20.0` and `0.20.1` won't cause such a slower speed.
Then, I tested ENV1 with Python=3.9.7 which is as same as ENV2 and it's still quicker than ENV2.
So, it's shouldn't be caused by Python version.

Then I tried to **degrade the proj to 8.0.1 in ENV1**:
```
The following packages will be DOWNGRADED:

  cartopy                             0.20.1-py39h8394fad_5 --> 0.20.0-py39h2103e0b_0
  geos                                    3.10.1-h9c3ff4c_1 --> 3.9.1-h9c3ff4c_2
  proj                                     8.2.0-h277dcde_0 --> 8.0.1-h277dcde_0
  pyproj                               3.3.0-py39h1b810de_0 --> 3.3.0-py39ha9a7ae0_0
  shapely                              1.8.0-py39h98e2149_4 --> 1.8.0-py39ha61afbd_0
```
**It's slow as same as ENV2.**

If I try to upgrade proj to 8.2.0 in ENV2 by `conda install proj=8.2.0`, it will raise conflicts:
```
Package pyproj conflicts for:
cartopy -> owslib[version='>=0.8.11'] -> pyproj[version='>=2']
basemap -> pyproj[version='>=1.9.3|>=1.9.3,<2']
cartopy -> pyproj[version='>=3.0']
.......
```

#### Code to reproduce

```
import time
import numpy as np
import cartopy.crs as ccrs
import matplotlib
matplotlib.use('Agg') 
import matplotlib.pyplot as plt 

offset = -40 
lon = np.linspace(offset, 360 + offset - 1, 3000)
lat = np.linspace(-60, 60 + 1, 500)
state = np.random.RandomState(51423)
data = state.rand(len(lat), len(lon))

def pyplot_test():
    start = time.time()
    fig, ax = plt.subplots(figsize=(4,4), subplot_kw=dict(projection=ccrs.Stereographic()))
    ax.coastlines()
    ax.pcolormesh(lon, lat, data, cmap='viridis', transform=ccrs.PlateCarree())
    plt.savefig('test_pyplot.jpg', dpi=300)
    print('pyplot save cost: ', time.time() - start)

pyplot_test()
```

#### Traceback 

```
ENV1:
pyplot save cost:  5.722408056259155

ENV2:
pyplot save cost:  34.269451379776
```

#### Some other useful info
I have tested the speed of one part:
https://github.com/SciTools/cartopy/blob/ecabeb883afb4d450f369afe4819ea743b8c73dc/lib/cartopy/mpl/geoaxes.py#L1900-L1902
It costs 1.0366578102111816 with ENV1 and 11.507331848144531 with ENV2.

**Comment by lukelbd** [comment]
Ok cool. Yep in your first example cartopy wasn't having to transform anything at all (because the default is native map coordinates rather than longitude-latitude), so it was faster. Keep in mind proplot's only dependency is `matplotlib` (no specific version) so your `proj` version differences aren't due to proplot -- something else is going on.

I also figured out that the speedup shown above is only relevant for *cartopy* plots. This fix seems obvious because it is obvious -- matplotlib's `Axes.get_tight_bbox()` *already* skips artists that are bounded by the subplot edge, however its method for skipping them (for some reason) fails with cartopy artists, while my method (for some reason) succeeds. May submit a cartopy PR at some point. Relevant lines:

https://github.com/matplotlib/matplotlib/blob/9765379ce6e7343070e815afc0988874041b98e2/lib/matplotlib/axes/_base.py#L4646-L4657
