### ISSUE TITLE
Wrong position of exponent label for extended colorbar

### ISSUE THREAD

**Issue by zxdawn** [lukelbd/proplot#327]
### Description

When the extent of colorbar is set, the exponent label will be overplayed.

### Steps to reproduce

```python
import proplot as pplt
import numpy as np

# Sample data
N = 18
state = np.random.RandomState(51423)
data = np.cumsum(state.rand(N, N), axis=0)*1e5

fig, axs = pplt.subplots()
axs.pcolor(data, sequential=True, colorbar='l', extend='max')
```

**Actual behavior**: [What actually happened]

![image](https://user-images.githubusercontent.com/30388627/150784749-89513135-9331-4dbf-98d6-641df1faceaa.png)

### Proplot version

Paste the results of `import matplotlib; print(matplotlib.__version__); import proplot; print(proplot.version)`here.
```
3.5.1
0.9.5.post202
```

**Comment by lukelbd** [comment]
It appears this is a matplotlib bug specific to left-hand-sidwe colorbars. Here's an example:

```python
import matplotlib.pyplot as plt
import numpy as np

N = 18
state = np.random.RandomState(51423)
data = 1e5 * np.cumsum(state.rand(N, N), axis=0)
fig, ax = plt.subplots()
m = ax.pcolor(data)
fig.colorbar(m, ax=ax, extend='max', location='left')
```

![tmp](https://user-images.githubusercontent.com/19657652/150914781-11eb1aa0-16ec-4426-80c1-a8f85487bc95.png)

**Comment by zxdawn** [comment]
Got it. Submitted: https://github.com/matplotlib/matplotlib/issues/22312
BTW, the issue exists for both the left and right colorbar.
