### ISSUE TITLE
 No module named 'proplot.config'

### ISSUE THREAD

**Issue by Mickychen00** [lukelbd/proplot#350]
I create an virtual environment with matplotlib 3.4.3. But I face problem " No module named 'proplot.config' " when I import proplot.
Is there any further dependency?

**Comment by lukelbd** [comment]
This sounds kind of odd -- nope there are no further dependencies. Do you mind copying and pasting the full traceback, so I can see where python is trying and failing to import `config`?

**Comment by lukelbd** [comment]
Going to close this for now but happy to re-open if you're still having the problem / can provide more info.
