### ISSUE TITLE
Empty legend of hist which only has edgecolor

### ISSUE THREAD

**Issue by zxdawn** [lukelbd/proplot#351]
### Description

The hist legend doesn't work for edgecolor.

### Steps to reproduce

```python
import proplot as pplt
import numpy as np

# Sample data
M, N = 300, 3
state = np.random.RandomState(51423)
x = state.normal(size=(M, N)) + state.rand(M)[:, None] * np.arange(N) + 2 * np.arange(N)

# Sample overlayed histograms
fig, ax = pplt.subplots(refwidth=4, refaspect=(3, 2))
ax.hist(x[:, 0], pplt.arange(-3, 8, 0.2), filled=True, edgecolor='indigo9', edgewidth=1, facecolor='none', legend='ul')
ax.hist(x[:, 1], pplt.arange(-3, 8, 0.2), filled=True, edgecolor='gray9', edgewidth=1, facecolor='none', legend='ul')
ax.hist(x[:, 2], pplt.arange(-3, 8, 0.2), filled=True, edgecolor='red9', edgewidth=1, facecolor='none', legend='ul')
```

**Expected behavior**: [What you expected to happen]

Showing correct legend.

**Actual behavior**: [What actually happened]

![image](https://user-images.githubusercontent.com/30388627/159365882-d89cf81c-8632-4e5d-a779-df58224096b0.png)

### Proplot version

```
3.5.1
0.9.5.post202
```

**Comment by syrte** [comment]
I think it is because you didn't specify the label keyword for pplt.hist.
Maybe you should try something with pplt.hist(..., label='whatever', ...).

**Comment by zxdawn** [comment]
@syrte Ha, you're right!

![image](https://user-images.githubusercontent.com/30388627/159481306-dc27e8b5-b405-42a2-a9ec-89d9ab4333bc.png)
