### ISSUE TITLE
cartopy/basemap pcolor plotting not working

### ISSUE THREAD

**Issue by bradyrx** [lukelbd/proplot#5]
Just digging into map plotting with `proplot`. I'm finding that `pcolorpoly` or `pcolormesh` is throwing an erroneous error.

POP coordinates file: http://s000.tinyupload.com/index.php?file_id=02400530605186772325

```python
import proplot as plot
import xarray as xr
import numpy as np
coords = xr.open_dataset('POP.x1.coords.nc')
data = np.random.rand(384,320)
data = xr.DataArray(data, dims=['nlat', 'nlon'])
data['TLAT'], data['TLONG'] = coords['TLAT'], coords['TLONG']
f, ax = plot.subplots(proj='hammer', basemap=False)
ax.pcolorpoly(data.TLONG, data.TLAT, data.T)
# ax.pcolormesh(data.TLONG, data.TLAT, data.T)
```

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-41-c6509b02180f> in <module>
      1 f, ax = plot.subplots(proj='hammer', basemap=False)
----> 2 ax.pcolorpoly(data.TLONG, data.TLAT, data.T, transform=ccrs.PlateCarree())

~/miniconda3/envs/python3/lib/python3.7/site-packages/proplot/subplots.py in iterator(*args, **kwargs)
     66                 ret = []
     67                 for ax in self:
---> 68                     res = getattr(ax, attr)(*args, **kwargs)
     69                     if res is not None:
     70                         ret += [res]

~/miniconda3/envs/python3/lib/python3.7/site-packages/proplot/base.py in decorator(rowmajor, *args, **kwargs)
    241                 x, y = utils.edges(x), utils.edges(y)
    242             elif Z.shape[0]!=xlen-1 or Z.shape[1]!=ylen-1:
--> 243                 raise ValueError(f'X ({"x".join(str(i) for i in x.shape)}) '
    244                         f'and Y ({"x".join(str(i) for i in y.shape)}) must correspond to '
    245                         f'nrows ({Z.shape[0]}) and ncolumns ({Z.shape[1]}) of Z, or its borders.')

ValueError: X (384x320) and Y (384x320) must correspond to nrows (320) and ncolumns (384) of Z, or its borders.
```

It's throwing an error for not having matching dims, despite having matching dims. Is this because `TLAT` and `TLONG` are 2D? This is required for something like POP and very common among many (if not all) ocean models. Note that this plots just fine calling `data.plot()` through xarray.

**Comment by bradyrx** [comment]
@lukelbd, oops. I was getting errors with either `data.T` or `data` and I think I submitted the wrong one to you, but glad you caught the bug.

---

So, it's working now, but slow as ever (even without plot.nbsetup()).

![screen shot 2019-01-22 at 8 10 49 am](https://user-images.githubusercontent.com/8881170/51544496-4ca0c400-1e1d-11e9-84ad-4f3324e43cd8.png)

---

You can get the sample dataset at https://github.com/bradyrx/climpred if you'd like to reproduce it. 

You can just run:
```python
from climpred.loadutils import open_dataset
data = open_dataset('MPI-control-3D')
```

**Comment by lukelbd** [comment]
Sure is slow lol. Noticed that. And don't know what the deal is with that missing chunk of data :/.

Will get to the bottom of this.

Also just curious on your opinion -- do you think I should just get rid of that "x-dimension by y-dimension" thing? Maybe it's just more confusing than not, and after all since python is a row-major language the rightmost dimension is technically the "first" dimension. I think I wrote that part because I was used to Matlab's defaults (Matlab is column-major). I find my datasets are usually time by z by y by x, so I end up just transposing them before feeding them into the plot functions.

**Comment by bradyrx** [comment]
I respect where the idea comes from (and chuckled at your documentation of it), but I think it makes more sense in the reversed fashion. I.e., default to row-major and give a keyword flag to turn on column-major. If you develop a decent user base (which you should) I would imagine this would be more of a headache and issue-raising thing than it's worth.

**Comment by lukelbd** [comment]
Yeah you're probably right. And anyway that whole "x by y" argument comes out of math notation, which so happens to use the *column-major* convention... so it probably doesn't make much sense. Was one of the first features I developed after switching from Matlab, never thought about it much.

Good idea on keeping a flag for column-major order. Now the options are `order='C'` and `order='F'` to match the [numpy convention](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.array.html), with `'C'` being the default.

Here's the new commit: a383036

**Comment by lukelbd** [comment]
Whoops: That commit didn't work; this (efbf859) should fix it.

**Comment by bradyrx** [comment]
@lukelbd,

Note that this is broken again. 2D coordinates plotting works with 6df7dbf2c4a18573c8af704fcd75d7119e1fda16, and a38303698852639ee857b9cec9ac875f78facf54 (and is speedy with my current use case)

However it breaks on efbf8590766a5e6f29b1aa774691dc7d77489029 and 89d1f822a3d1cec31fa8ad199f02d034e7f22b8d.

The error message is similar to before:

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-1311c8f0b51f> in <module>
      3                        proj='hammer', proj_kw={'lon_0':0},
      4                        basemap=False)
----> 5 ax.pcolorpoly(ds.TLONG, ds.TLAT, ds)

~/Desktop/ph_example/proplot/proplot/subplots.py in iterator(*args, **kwargs)
     66                 ret = []
     67                 for ax in self:
---> 68                     res = getattr(ax, attr)(*args, **kwargs)
     69                     if res is not None:
     70                         ret += [res]

~/Desktop/ph_example/proplot/proplot/base.py in decorator(order, *args, **kwargs)
    258                     x, y = utils.edges(x), utils.edges(y)
    259             elif Z.shape[1]!=xlen-1 or Z.shape[0]!=ylen-1:
--> 260                 raise ValueError(f'X ({"x".join(str(i) for i in x.shape)}) '
    261                         f'and Y ({"x".join(str(i) for i in y.shape)}) must correspond to '
    262                         f'ncolumns ({Z.shape[1]}) and nrows ({Z.shape[0]}) of Z, or its borders.')

ValueError: X (384x320) and Y (384x320) must correspond to ncolumns (320) and nrows (384) of Z, or its borders.
```

**Comment by lukelbd** [comment]
It should be fixed now... was just a dumb mistake. I had `xlen, ylen = x.shape[0], y.shape[-1]` in the `_check_edges` function instead of `xlen, ylen = x.shape[-1], y.shape[0]`.
