### ISSUE TITLE
Export custom colormaps in readable formats

### ISSUE THREAD

**Issue by bradyrx** [lukelbd/proplot#56]
I think it would be useful to have an `export=bool` command on `plot.Colormap`. Currently, `save=True` just saves it to `~/.proplot/cmaps` as a json that seems to be readable to just `proplot`. It would be great to be able to export it as an xml, hex, etc. to then import into other tools and software.

**Comment by lukelbd** [comment]
You read my mind :)

In #57, I'm implementing all colormaps as subclasses of the `matplotlib.colors.Colormap` class. The subclass will add a `save()` method that can take optional arguments for the save format, save location, etc. Then passing `save=True` to `plot.Colormap()` will just call `cmap.save()`, where the default `cmap.save()` behavior will be to save in `~/.proplot/cmaps`.

**Comment by lukelbd** [comment]
Done! See #57 

Example usage:

```python
import proplot as plot
cmap = plot.Colormap(('goldenrod',  'red')) # perceptually uniform transition between colors
cmap.save('file.txt') # saves RGB table in current directory
```

See [the docs](https://proplot.readthedocs.io/en/latest/api/proplot.styletools.LinearSegmentedColormap.save.html#proplot.styletools.LinearSegmentedColormap.save) for details.

**Comment by bradyrx** [comment]
Awesome!

**Comment by lukelbd** [comment]
Also (thought this was cool) I changed `__repr__` and `__str__` for the new colormap classes, which makes it easy to work with them interactively. Examples:

```python
>>> plot.Colormap('Blues') # colorbrewer
LinearSegmentedColormap({
 'name': 'Blues',
 'red': [0.969, ..., 0.031],
 'green': [0.984, ..., 0.188],
 'blue': [1.000, ..., 0.420],
 'alpha': [1.000, ..., 1.000],
})

>>> plot.Colormap('dark red') # arbitrary named color
PerceptuallyUniformColormap({
 'name': '_no_name',
 'space': 'hsl',
 'hue': [12.169, ..., 12.169],
 'saturation': [99.994, ..., 99.994],
 'luminance': [100.000, ..., 26.464],
 'alpha': [1.000, ..., 1.000],
})

>>> plot.Colormap('fire') # ProPlot map
PerceptuallyUniformColormap({
 'name': 'Fire',
 'space': 'hsl',
 'hue': [72.169, ..., -27.831],
 'saturation': [90.000, ..., 60.000],
 'luminance': [100.000, ..., 15.000],
 'alpha': [1.000, ..., 1.000],
})

>>> plot.Colormap('538') # "color cycle"
ListedColormap({
 'name': '538',
 'colors': ['#008fd5', '#fc4f30', '#e5ae38', '#6d904f', '#8b8b8b', '#810f7c'],
})
```
