### ISSUE TITLE
Cannot add text to projection axes

### ISSUE THREAD

**Issue by bradyrx** [lukelbd/proplot#60]
Currently, the `text` wrapper for `proplot` cannot handle projecting to geoaxes, making it impossible to accurately place text on a map projection. For `matplotlib` one just passes a `transform=ccrs.PlateCarree()` for example to the `ax.text()` to interpret the values as coordinates on the map:

```python
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature

f, ax = plt.subplots(subplot_kw=dict(projection=ccrs.SouthPolarStereo(central_longitude=-70)))
ax.set_extent([-180, 180, -90, -40], ccrs.PlateCarree())
ax.add_feature(cfeature.LAND, color='#d3d3d3')

ax.text(120, -83, 'test', transform=ccrs.PlateCarree())
```

<img width="261" alt="Screen Shot 2019-10-31 at 2 39 36 PM" src="https://user-images.githubusercontent.com/8881170/67984429-4c272c00-fbec-11e9-8b44-00af26912eb2.png">

`proplot` breaks when one tries to place `ccrs.PlateCarree()` into the `transform` keyword for the text wrapper. And the options of `data`, `axes`, `figure` don't fix this problem. Perhaps an extra keyword such as `geoaxes` could handle this?

```python
import proplot as plot

f, ax = plot.subplots(proj='spstere', proj_kw={'central_longitude': -70})

ax.text(120, -83, 'test', color='w', fontname='Helvetica')

ax.format(land=True, boundinglat=-40)
```

<img width="241" alt="Screen Shot 2019-10-31 at 2 39 38 PM" src="https://user-images.githubusercontent.com/8881170/67984437-4fbab300-fbec-11e9-836f-04b046a64a90.png">

**Comment by lukelbd** [comment]
Thanks for the report, this was a really simple fix: 29b7d6df. For cartopy axes, `text(..., transform='data')` (the default behavior) now corresponds to longitude-latitude coordinates. You can use `transform='map'` or `transform=ax.transData` to use map projection coordinates. 

Tried to also fix this for basemap, but apparently the `Basemap` class doesn't support positioning text in longitude-latitude coordiantes.
