### ISSUE TITLE
No need to flip to get edges

### ISSUE THREAD

**Issue by stefraynaud** [lukelbd/proplot#67]
Hi,

I don't think there is any need to flip the array when coordinates are decreasing here:
https://github.com/lukelbd/proplot/blob/5ed5e8d02c8ca14a58789e414a0aa2ea5a600e8f/proplot/utils.py#L159

The linear interpolations and extrapolations are always valid.

**Comment by lukelbd** [comment]
You're 100% right -- don't know what I was thinking. Thanks for #68.

**Comment by lukelbd** [comment]
Closed by #68
