### ISSUE TITLE
Date time axis not working properly

### ISSUE THREAD

**Issue by bradyrx** [lukelbd/proplot#8]
The `plot.plot()` command is currently not interpreting datetimes correctly and is instead plotting in the "days since 0000 ..." units.

```python
import numpy as np
dat = np.random.rand(612,)
time = np.arange('1964-01', '2015-01', dtype='datetime64[M]')
# proplot
f, ax = plot.subplots(axwidth=5, aspect=4)
ax.plot(time, dat)
# matplotlib
f, ax = plt.subplots(figsize=(6,2))
ax.plot(time, dat)
```

proplot version:

<img width="521" alt="screen shot 2019-01-31 at 4 32 27 pm" src="https://user-images.githubusercontent.com/8881170/52092762-d5360780-2575-11e9-9686-3a9a69b5733d.png">

matplotlib version:

<img width="489" alt="screen shot 2019-01-31 at 4 32 37 pm" src="https://user-images.githubusercontent.com/8881170/52092763-d6673480-2575-11e9-90aa-5e85892a03d2.png">

**Comment by lukelbd** [comment]
Unfortunately the time axis stuff is super untested (mainly because I somehow haven't needed to work with time axes in the past 2 years). Will look into this; it should be a simple fix.

**Comment by lukelbd** [comment]
Fixed it. It turns out if you change the tick label formatter manually, a toggle is switched (`isDefault_majfmt`) that tells matplotlib not to automatically change the formatter when it encounters certain types of data, like datetime64 coordinates. Now I just un-switch that toggle.
