### ISSUE TITLE
Remember metadata when passing mappables to colorbar()

### ISSUE THREAD

**Issue by mickaellalande** [lukelbd/proplot#81]
I have another suggestion of enhancement regarding what **Cartopy** does. By default, **ProPlot** uses the `long_name` attribute of a DataArray as a `title` of the figure, but not the `units` attribute. Here is the default behavior of **Cartopy** when doing a plot (data: [ens_avg_snow_cyclic.zip](https://github.com/lukelbd/proplot/files/3922734/ens_avg_snow_cyclic.zip)):

```python
import xarray as xr
import proplot as plot

ens_avg_snow_cyclic = xr.open_dataarray('ens_avg_snow_cyclic.nc')
ens_avg_snow_cyclic.plot()
```
![cartopy_units](https://user-images.githubusercontent.com/20254164/70157882-9ea9ab80-16b6-11ea-92d6-c4502c693b14.jpg)

It automatically puts the `long_name` and `units` attribute of the DataArray beside the color bar. In addition, it writes as a title the coordinates left (I didn't do any projection, the goal is only to show the labels here).

It would be nice to at least have the `units` after the title in **ProPlot** too, in addition to the actual default behavior shown here:
```python
f, axs = plot.subplots(proj='cyl', width=8)

m = axs[0].contourf(ens_avg_snow_cyclic, cmap='BuRd')

f.colorbar(m)

axs.format(
    geogridlinewidth=0.5, geogridcolor='gray8', geogridalpha=0.5, labels=True, 
    coast=True, ocean=True, oceancolor='gray3', latlim=(20,90),
    suptitle=str(ens_avg_snow_cyclic.season.values) + ' climatology'
)
```
![proplot_default](https://user-images.githubusercontent.com/20254164/70158201-242d5b80-16b7-11ea-9a4f-deb705182cb0.jpg)

Like for example (here are 3 different possibilies I am thinking):
![proplot_default_1](https://user-images.githubusercontent.com/20254164/70158278-458e4780-16b7-11ea-839f-f632d32c8bb3.jpg)
![proplot_default_2](https://user-images.githubusercontent.com/20254164/70158287-47f0a180-16b7-11ea-9bf2-0c52f274ce38.jpg)
![proplot_default_3](https://user-images.githubusercontent.com/20254164/70158290-4921ce80-16b7-11ea-9f7f-3b2b9db6c0f5.jpg)

Or having the same behavior as **Cartopy** like the 2nd example and putting as a title the left coordinates as `coord_name = values`. Here it is the season, but usually, if we select a date, it shows `time = ...`. After it doesn't have to be like Cartopy, in my opinion adding at least the units would be already nice :)

**Comment by lukelbd** [comment]
For now if you pass `colorbar='r'` or `colorbar=True` to your `axs[0].contourf` command, it will automatically label the colorbar with the `long_name` and `units`. Currently, automatic labeling is 100% controlled from plotting commands -- so it is only possible to automatically label colorbars and legends if you generate them on-the-fly by passing the corresponding keyword argument to your plotting command.

I think I can fix this by adding a hidden `_metadata` attribute to artists generated by ProPlot plotting methods, and then when `legend()` or `colorbar()` receives an artist with this attribute, it can automatically apply the labels.

I really like those examples! This feature should definitely be configurable. We can add keyword arguments to determine where the labels and units are placed, and maybe some `rc` options. I *think* the defaut behavior should be what it is now though -- generally units are not something that show up on axis labels, colorbars, and legends, not titles.

It wil also definitely be useful if ProPlot can try to detect *singleton or "scalar" dimensions* and add those values to the title, like how your example shows the time slice.

**Comment by mickaellalande** [comment]
Great ok, yes `colorbar='r'` works well! Thus:

```python
f, axs = plot.subplots(proj='cyl', width=8)

m = axs[0].contourf(ens_avg_snow_cyclic, cmap='BuRd', colorbar='r')

axs.format(
    geogridlinewidth=0.5, geogridcolor='gray8', geogridalpha=0.5, labels=True, 
    coast=True, ocean=True, oceancolor='gray3', latlim=(20,90),
    suptitle=str(ens_avg_snow_cyclic.season.values) + ' climatology', title=''
)
```

Gives the same result as the 2nd example without having to pass the units :)

However, if I replace by `colorbar=True` it through an error:
```python
ValueError: Invalid on-the-fly location None. Must be a preset location. See Axes.colorbar.
```
I guess we need to set the location first?

**Comment by mickaellalande** [comment]
I also just realized that if I use non-cyclic data and use the option `globe=True` in addition to `colorbar='r'` the `long_name` and `units` don't show up anymore besides the color bar. It works only without the option `globe=True`...

**Comment by lukelbd** [comment]
@mickaellalande Thanks for letting me know -- just fixed this in the latest version.

https://github.com/lukelbd/proplot/blob/ecb3c899cbd4b7cd2aeda72bb7c8fa62dce2e82a/proplot/wrappers.py#L650-L654

**Comment by lukelbd** [comment]
This is now implemented on master -- all "autoformat" info is now attached to outgoing mappables and when they are passed into `legend()` or `handle()` the default label is applied. Here's a very quick example:

```python
 import proplot as pplt
 import xarray as xr
 fig, ax = pplt.subplots()
 data = xr.DataArray(np.random.rand(10, 10), attrs={'long_name': 'variable'})
 m = ax.pcolor(data)
 ax.colorbar(m, loc='b')
```

![cbar](https://user-images.githubusercontent.com/19657652/129957413-04d4239b-ab2e-46b7-a96a-b6612c95b141.png)
