### ISSUE TITLE
Minor issue // plot.show_cycles() throws AttributeError

### ISSUE THREAD

**Issue by Thomas-Moore-Creative** [lukelbd/proplot#90]
```python
import proplot as plot
f = plot.show_cycles()
```

Thanks for this great package!
I'm running 0.3.1 and just working my way through your docs.  I noted above from your docs throws the following error:

`AttributeError: 'LinearSegmentedColormap' object has no attribute 'colors'`

**Comment by lukelbd** [comment]
No problem :). I figured this out: The current `show_cycles` command is fragile; it just tracks cycle _names_, and evidently you have overwritten a cycle by that name with a colormap.

The next version includes changes to `show_cycles` that will solve this issue: `plot.show_cycles` will be identical to `plot.show_cmaps`, the only difference being that `plot.show_cmaps` displays `LinearSegmentedColormap`s (continuous color gradations) while `plot.show_cycles` displays `ListedColormap`s (discrete color sets).

**Comment by lukelbd** [comment]
This should be fixed by #98. It is published in the latest (0.4.0) release; use `pip install --upgrade proplot` to upgrade.
